bcgov/jag-dps

- .github/pull_request_template.md
PR contains the standardized PR template and hidden github directory
> added hidden github directory and pr template file

- README.md
- Adding an initial `Readme` to the repository. 
no test required.
this PR fixes jira ticket: **DPSIM-78**
> Add readme to the dps repo

- README.md
I made a small change to the README.md file to prove the flow. This is my first pull request. 
It was fully tested by looking at the spelling of the test I added. 
this PR fixes jira ticket: No JIRA, testing only
> Added small update to README.md to test my knowledge of the PR flow.

- README.md
- docker-compose.yml
- src/paymentservice/Dockerfile
This pr includes the following proposed changes:
- A new docker image for the payment service app.
After running
```bash
docker-compose up
```
you should get:
Postman test:
Locally running docker-compose up
this PR fixes jira ticket: **DPSIM-81**
> Dockerized Payment service application

- README.md
- a fix to the readme documentation for endpoints
> Fixed error on http verb

- src/paymentservice/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/paymentservice/BamboraConfiguration.java
- src/paymentservice/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/paymentservice/CalculateSinglePayment.java
- src/paymentservice/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/paymentservice/types/BeanstreamEndpointResponse.java
- src/paymentservice/src/main/resources/application.properties
- src/paymentservice/src/test/java/ca/bc/gov/open/pssg/rsbc/dps/paymentservice/PaymentserviceApplicationTests.java
These changes are for reading the bambor/beanstream configuration properties
> DPSIM 79 - Bambora config changes

- .github/workflows/maven-test-pr.yml
- README.md
- docker-compose.yml
- src/paymentservice/Dockerfile
- src/paymentservice/README.md
- src/paymentservice/src/main/resources/application-cloud.properties
- (DPSIM-89)[https://justice.gov.bc.ca/jira/browse/DPSIM-89] - Adding support for environment variables in cloud environment
Tested locally with docker
this PR fixes jira ticket: **DPSIM-89**
> Added support for cloud configuration

- README.md
- src/paymentservice/README.md
- src/paymentservice/pom.xml
This Pull Request includes the following changes:
- [DPSIM-77](https://justice.gov.bc.ca/jira/browse/DPSIM-77) - Expose Application Health
a new endpoint is available at `/paymentservice/actuator/health`
Tested locally, got response from actuator/health
this PR fixes jira ticket: **DPSIM-77**
> Added actuator dependency

- src/paymentservice/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/paymentservice/BamboraConfiguration.java
This PR is to add error handling to the BamboraConfiguration class to handle if any of the config params(approved,declined,error) are missing
> DPSIM86 error handling 

- src/paymentservice/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/paymentservice/BamboraConfiguration.java
- src/paymentservice/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/paymentservice/CalculateSinglePayment.java
Adding  2 log statements in BamboraConfiguration class. Error message when config values are not found and a debug message when its read successfully
> adding Logging to BamboraConfiguration

- src/paymentservice/README.md
- src/paymentservice/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/paymentservice/configuration/SwaggerConfig.java
- src/paymentservice/src/main/resources/application-cloud.properties
- [DPSIM-144](https://justice.gov.bc.ca/jira/browse/DPSIM-144) - Set default value for swagger ui to false
Locally on docker + mvn
this PR fixes jira ticket: **DPSIM-144**
> Set default value for swagger ui

- .gitignore
- .splunk/conf/inputs.conf
- .splunk/conf/outputs.conf
- README.md
- docker-compose.yml
- src/service-api/conf/nginx.conf
this PR includes the following change:
- [DPSIM-146](https://justice.gov.bc.ca/jira/browse/DPSIM-146) - add dps service api log to splunk
A couple of issues will need to be addressed:
- Environment variables in splunk `inputs.conf`
- Using named volumes in docker instead of mounting a local directory
This adds the following logs to splunk:
local docker
this PR fixes jira ticket: **DPSIM-146**
> Added universal forwarder for dps service api

- src/figvalidationservice/pom.xml
- src/figvalidationservice/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/figvalidationservice/FigValidationServiceApp.java
- src/figvalidationservice/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/figvalidationservice/FigaroValidation.java
- src/figvalidationservice/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/figvalidationservice/FigaroValidationImpl.java
- src/figvalidationservice/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/figvalidationservice/FigaroValidationServiceConstants.java
- src/figvalidationservice/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/figvalidationservice/LocateMatchingApplicantsController.java
- src/figvalidationservice/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/figvalidationservice/exception/FigaroValidationServiceException.java
- src/figvalidationservice/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/figvalidationservice/types/LocateMatchingApplicantsRequest.java
- src/figvalidationservice/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/figvalidationservice/types/LocateMatchingApplicantsResponse.java
Basic endpoint minus ORDS connectivity
Addition of Basic controller MINUS ORDS connectivity.  
Yes. Ran basic mvn commands and tested controller responds exactly as legacy endpoint. 
this PR fixes jira ticket: **DPSIM-99**
> DPSIM-99_1: Added LocateMatchingApplicants controller to FIGARO validation services

- src/dpsvalidationservice/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsvalidationservice/GetValidOpenDFCMCase.java
- src/dpsvalidationservice/src/test/java/ca/bc/gov/open/pssg/rsbc/dps/dpsvalidationservice/DpsValidationserviceApplicationTests.java
This PR includes a controller which maps to getValidOpenDFCMCase request and a test case . This does not include any logic as in its webmothd yet. It mocks and sends back a xml response for now . Handling errors and exceptions will be added later. 
mvn package
java -jar .\target\dpsvalidationservice-0.0.1-SNAPSHOT.jar
access the end point from browser/postman 
http://localhost:8082/dpsvalidationservice/getValidOpenDFCMCase/?driversLicense=1234567&surcode=345
xml response 
<GetValidOpenDFCMCase>
<int>2</int>
<caseDesc>ROUTINE - PROFESSIONAL</caseDesc>
</GetValidOpenDFCMCase>
> created a controller which returns a mocked response 

- src/figvalidationservice/README.md
- src/figvalidationservice/pom.xml
- src/figvalidationservice/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/figvalidationservice/LocateMatchingApplicantsController.java
- src/figvalidationservice/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/figvalidationservice/configuration/SwaggerConfig.java
- src/figvalidationservice/src/main/resources/application.properties
Added swagger support and updated application level README.
mvn package and spring-boot:run (operation and swagger testing). 
this PR fixes jira ticket: **DPSIM-99**
> DPSIM-99_3: Added swagger support and updated project level README.

- src/dpsvalidationservice/pom.xml
- src/figvalidationservice/pom.xml
- src/paymentservice/pom.xml
- src/pom.xml
Create Parent Child POM relationship between microservices
Following changes are included in the pull request.
1.Added a new parent pom in the root folder and included all the common dependencies,properties which are referenced from all the services in the parent pom.
2. included paymentservice,dpsvalidationservice and figvalidationservice as modules.
3.removed the common dependencies and properties from pom file of  paymentservice,dpsvalidationservice and figvalidationservice so that the dependency will be included from parent pom.
4.added 'dps' as the parent in paymentservice,dpsvalidationservice and figvalidationservice 
Maven build and run all the spring application in local environment
this PR fixes jira ticket: …
> Changes for DPSIM-150

- README.md
- src/pom.xml
- A list of profiles for each spring boot applications
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
> Added profiles in POM file for all our projects

- docker-compose.yml
- src/Dockerfile
- a generic docker file for building dps services
locally on docker
> created a generic docker file

- src/figvalidationservice/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/figvalidationservice/FigaroValidation.java
- src/figvalidationservice/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/figvalidationservice/FigaroValidationImpl.java
- src/figvalidationservice/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/figvalidationservice/FigaroValidationServiceConstants.java
- src/figvalidationservice/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/figvalidationservice/LocateMatchingApplicantsController.java
- src/figvalidationservice/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/figvalidationservice/ValidateApplicantServiceController.java
- src/figvalidationservice/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/figvalidationservice/types/LocateMatchingApplicantsResponse.java
- src/figvalidationservice/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/figvalidationservice/types/ValidateApplicantServiceRequest.java
- src/figvalidationservice/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/figvalidationservice/types/ValidateApplicantServiceResponse.java
- src/figvalidationservice/src/main/resources/logback-splunk.xml
- src/figvalidationservice/src/main/resources/logback.xml
Additional Swagger annotation support and basic logging
Added basic endpoint/controller for validateApplicantService
Ran mvn spring-boot:run / tested swagger documentation. Tested logging output in the event of exception. 
- [] I have made corresponding changes to the documentation
- [] I have added tests that prove my fix is effective or that my feature works
- [] New and existing unit tests pass locally with my changes
this PR fixes jira ticket: **DPSIM-119**
> DPSIM-119_1: Added basic endpoint/controller for validateApplicantService

- src/figvalidationservice/src/test/java/ca/bc/gov/open/pssg/rsbc/dps/figvalidationservice/FigValidationServiceAppTests.java
Small fix to correct test
mvn package
this PR fixes jira ticket: **fix**
> Small fix to correct test

- .github/workflows/maven-test-pr.yml
- src/pom.xml
- A new profile "all" to build all applications
- fix to the github actions to run test on all applications
run mvn
> Fixed the gitactions + created a all profile to build all apps

- src/dpsvalidationservice/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsvalidationservice/GetValidOpenDFCMCase.java
- src/dpsvalidationservice/src/main/resources/logback.xml
- src/dpsvalidationservice/src/test/java/ca/bc/gov/open/pssg/rsbc/dps/dpsvalidationservice/DpsValidationserviceApplicationTests.java
Added logback xml config to DPSValidationService . 
Added log statement to the class
Run the app from IDE 
access the endpoint - http://localhost:8082/dpsvalidationservice/getValidOpenDFCMCase/?driversLicense=123&surcode=345
Log statement is printed in the console
> Logback xml and logging

- README.md
- src/figvalidationservice/src/test/java/ca/bc/gov/open/pssg/rsbc/dps/figvalidationservice/FigValidationServiceAppTests.java
Added test for validateApplicants service, updated main README.md with service endpoints. 
mvn package
this PR fixes jira ticket: **DPSIM-119**
> Dpsim 119 2: Added test for validateApplicants service. 

- README.md
- docker-compose.yml
- src/service-api/conf/nginx.conf
- [DPSIM-102](https://justice.gov.bc.ca/jira/browse/DPSIM-102) - Create Route in DPS Api Router for LocateMatchingApplicants
Local running docker
this PR fixes jira ticket: **DPSIM-102**
> Added new route for the figvalidatioserver

- src/figvalidationservice/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/figvalidationservice/FigaroValidation.java
- src/figvalidationservice/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/figvalidationservice/FigaroValidationImpl.java
- src/figvalidationservice/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/figvalidationservice/ValidateApplicantForSharingController.java
- src/figvalidationservice/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/figvalidationservice/types/ValidateApplicantForSharingRequest.java
- src/figvalidationservice/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/figvalidationservice/types/ValidateApplicantForSharingResponse.java
- src/figvalidationservice/src/test/java/ca/bc/gov/open/pssg/rsbc/dps/figvalidationservice/FigValidationServiceAppTests.java
Included controller changes for 'ValidateApplicantForSharing' Figaro validation service
Following changes are included in the PR :
1.Controller class for ValidateApplicantForSharing ,Figaro validation service to handle **'/validateApplicantForSharing'** requests
2.Request and Response classes.
3.Included functionality in 'FigaroValidationImpl' to handle '/validateApplicantForSharing' requests
1. maven build and run figvalidationservice application.
2. go to http://localhost:8081/figvalidationservice/validateApplicantForSharing? applPartyId=43248&jurisdictionType=WWCH URL 
3. get the dummy response message
this PR fixes jira ticket: **https://justice.gov.bc.ca/jira/browse/DPSIM-106**
> Initial commit for DPSIM-106

- src/dpsvalidationservice/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsvalidationservice/DpsValidationServiceConstants.java
- src/dpsvalidationservice/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsvalidationservice/DpsValidationserviceConstants.java
- src/dpsvalidationservice/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsvalidationservice/GetValidOpenDFCMCase.java
- src/dpsvalidationservice/src/test/java/ca/bc/gov/open/pssg/rsbc/dps/dpsvalidationservice/DpsValidationserviceApplicationTests.java
1) Introduced a class to keep all the constants used .
2) Added a exception handler function to handle missing parameters
3) Updated the controller method to check the pattern matching of input parameters
Run the application .
accessed the endpoints - 
Success case - 
http://localhost:8082/dpsvalidationservice/getValidOpenDFCMCase?driversLicense=1234567&surcode=PEL
returned a valid xml with a response
Error Case-
1) http://localhost:8082/dpsvalidationservice/getValidOpenDFCMCase?&surcode=345
returned a xml with -2 code 
> DPSIM 160 - Handling missing params and error handling

- src/figvalidationservice/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/figvalidationservice/FigaroValidation.java
- src/figvalidationservice/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/figvalidationservice/FigaroValidationImpl.java
- src/figvalidationservice/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/figvalidationservice/ValidateApplicantPartyIdController.java
- src/figvalidationservice/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/figvalidationservice/types/ValidateApplicantPartyIdResponse.java
Basic service, and swagger annotations.
Added validateApplicantPartyId operation.
mvn package, mvn spring-boot:run and Swagger-ui testing to ensure the new operation has been properly documented.  
this PR fixes jira ticket: **DPSIM-113**
> DPSIM-113_1: Added validateApplicantPartyId operation.

- README.md
- src/figvalidationservice/README.md
- src/figvalidationservice/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/figvalidationservice/ValidateApplicantForSharingController.java
- src/figvalidationservice/src/test/java/ca/bc/gov/open/pssg/rsbc/dps/figvalidationservice/FigValidationServiceAppTests.java
- src/paymentservice/README.md
Added test for validateApplicantPartyId, Cleaned up README.md (both  Figaro validation service and project head)
mvn package to run tests. 
this PR fixes jira ticket: **DPSIM-113**
> DPSIM-113_2: Added test for validateApplicantPartyId.

- .env.template
- README.md
- src/dpsvalidationservice/pom.xml
- src/figvalidationservice/README.md
- src/figvalidationservice/figcrpords.json
- src/figvalidationservice/pom.xml
- src/figvalidationservice/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/figvalidationservice/configuration/OrdsFigcrConfig.java
- src/figvalidationservice/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/figvalidationservice/configuration/OrdsFigcrProperties.java
- src/figvalidationservice/src/main/resources/application.properties
- src/figvalidationservice/src/test/resources/test.properties
[DPSIM-100](https://justice.gov.bc.ca/jira/browse/DPSIM-100) - Create ORDS Java Spring boot Client for figValidationService
Locally using docker
this PR fixes jira ticket: **DPSIM-100**
> Added ords client

- README.md
- docker-compose.yml
- src/dpsvalidationservice/README.md
- src/dpsvalidationservice/src/main/resources/application.properties
- src/service-api/conf/nginx.conf
Added routing for /dpsvalidationservice in service-api 
Updated readme with details of DPS validation Service
Corrected the ports in the hyperlinks of figvalidationservice and paymentservice
docker-compose up --build
access endpoints and verified the xml response for each 
http://localhost:8080/paymentservice/bamboraconfiguration
http://localhost:8080/figvalidationservice/locateMatchingApplicants
http://localhost:8080/dpsvalidationservice/getValidOpenDFCMCase/?driversLicense=1234567&surcode=PEL
> DPSIM 94 - Adding api routing , and readme updates

- README.md
- src/dpsvalidationservice/pom.xml
1) Add actuator dependency for health check 
2) Update readme with DPS Validation endpoints.
run the application 
tested the health check endpoints 
> adding health check to the application

- src/dpsvalidationservice/pom.xml
- src/dpsvalidationservice/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsvalidationservice/DpsValidationServiceConstants.java
- src/dpsvalidationservice/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsvalidationservice/dfcsm/GetValidOpenDFCMCase.java
- src/dpsvalidationservice/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsvalidationservice/dfcsm/ValidationController.java
- src/dpsvalidationservice/src/test/java/ca/bc/gov/open/pssg/rsbc/dps/dpsvalidationservice/DpsValidationserviceApplicationTests.java
- Refactored response to use java object.
this change was needed to integrate with DPSIM-163
Locally
this PR fixes jira ticket: **DPSIM-163**
> Refactored controller

- src/dpsvalidationservice/.gitignore
Adding a .gitignore 
mvn package
> adding .gitignore 

- src/dpsvalidationservice/pom.xml
- src/figvalidationservice/figcrpords.json
To fix the warnings 
Removed the dependency 
Added a field operationId in the json  
mvn clean
mvn package
> fix duplicate dependency & some build warnings

- src/service-api/conf/nginx.conf
- [DPSIM-165](https://justice.gov.bc.ca/jira/browse/DPSIM-165) - NGINX failing on docker
It feels like this configuration is only going to work for docker, openshift would need it's own configuration to get our nginx service api up.
Locally using docker and connected to ords
this PR fixes jira ticket: **DPSIM-165**
> Fixing nginx configuration

- src/dpsvalidationservice/dfcmsords.yaml
- src/dpsvalidationservice/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsvalidationservice/configuration/OrdsDfcmsConfig.java
- src/dpsvalidationservice/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsvalidationservice/dfcsm/ValidationController.java
- src/dpsvalidationservice/src/test/java/ca/bc/gov/open/pssg/rsbc/dps/dpsvalidationservice/DpsValidationserviceApplicationTests.java
- src/dpsvalidationservice/src/test/java/ca/bc/gov/open/pssg/rsbc/dps/dpsvalidationservice/ValidationControllerTest.java
- rename DFCRMS to DFCMS in swagger definition
Run unit tests + docker
> Fixed spelling error in api name

- src/dpsvalidationservice/src/test/java/ca/bc/gov/open/pssg/rsbc/dps/dpsvalidationservice/ValidationControllerTest.java
- Added a test to cover api client exception.
Running the unit tests
> Added test to cover client exception 

- README.md
- tests/postman/DPS-Service-Api.postman_collection.json
- tests/postman/dps-env.postman_environment.json
- a postman collection and instructions to run with `newman`
Locally using postman!
> Added postman tests

- README.md
- tests/postman/DPS-Service-Api.postman_collection.json
- tests/postman/dps-env.postman_environment.json
- Adding test case in postman for the payment service
using postman
> Added test for payment service

- src/paymentservice/src/test/java/ca/bc/gov/open/pssg/rsbc/dps/paymentservice/BamboraClientImplTest.java
- Added a new test for the Bambora client implementation
Run unit tests
> Added new unit test for bamboraclient impl

- src/paymentservice/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/paymentservice/CrcController.java
- src/paymentservice/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/paymentservice/types/BeanstreamEndpointResponse.java
- src/paymentservice/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/paymentservice/types/SinglePaymentResponse.java
- src/paymentservice/src/test/java/ca/bc/gov/open/pssg/rsbc/dps/paymentservice/CrcControllerTest.java
Corrects the naming of the response object root node. 
Checked expected change was in place. 
Complete rebuild of project complete with running of existing tests. 
this PR fixes jira ticket: **Fix**
> Fixed root node naming of BeanstreamEndpointResponse

- openshift/templates/sonarqube.dc.yaml
Deployment config for sonarqube on openshift.
Have to test after deployment.
> added deploy config for sonarqube

- Jenkinsfile
Adding integration for Sonarqube to our current jenkinsfile.
It will be tested on the first merge to master - so possibly this PR.
> jenkinsfile updated for quality checks

- src/paymentservice/src/test/java/ca/bc/gov/open/pssg/rsbc/dps/paymentservice/BamboraClientImplTest.java
- src/paymentservice/src/test/java/ca/bc/gov/open/pssg/rsbc/dps/paymentservice/PaymentserviceApplicationTests.java
This Pull Request includes the following changes:
- New test to validate the xml is lowercase.
Unit tests only
> Added test for xml

- src/dpsvalidationservice/pom.xml
- src/figvalidationservice/pom.xml
- disable tests for models in auto generated code.
this is not needed.
Building the app locally.
> Disable generated model tests for swagger

- src/dpsvalidationservice/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsvalidationservice/dfcsm/ValidationController.java
> Surcode Optional

- src/figvalidationservice/figcrpords.yaml
- src/figvalidationservice/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/figvalidationservice/FigaroValidation.java
- src/figvalidationservice/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/figvalidationservice/FigaroValidationImpl.java
- src/figvalidationservice/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/figvalidationservice/ValidateApplicantServiceController.java
- src/figvalidationservice/src/test/java/ca/bc/gov/open/pssg/rsbc/dps/figvalidationservice/FigValidationServiceAppTests.java
- src/figvalidationservice/src/test/java/ca/bc/gov/open/pssg/rsbc/dps/figvalidationservice/ValidateApplicantServiceControllerTest.java
Update ORDS Java Spring boot Client with new ords endpoint  for 'validateApplicantForSharing' in Figarovalidation service
NOT Included : Unit test for the service.
Updated validateApplicantForSharing controller to get data from ORDS.
To test the changes i local environment 
- mvn clean install figvalidationservice
- run the application.
- test the Rest using URL : http://localhost:8081/figvalidationservice/validateApplicantService?orgPartyId=442&applPartyId=32432
- The response should match the response from actual ORDS request https://dev.jag.gov.bc.ca/ords/deva/figcrpords/web/validateOrgApplicantService?org_party_id=442&appl_party_id=32432
this PR fixes jira ticket: **https://justice.gov.bc.ca/jira/browse/DPSIM-120**
> Changes for DPSIM-120

- src/figvalidationservice/figcrpords.yaml
- src/figvalidationservice/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/figvalidationservice/configuration/OrdsFigcrConfig.java
- src/figvalidationservice/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/figvalidationservice/facility/FacilityController.java
- src/figvalidationservice/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/figvalidationservice/facility/FacilityService.java
- src/figvalidationservice/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/figvalidationservice/facility/FacilityServiceImpl.java
- src/figvalidationservice/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/figvalidationservice/facility/ValidateFacilityPartyRequest.java
- src/figvalidationservice/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/figvalidationservice/facility/ValidateFacilityPartyResponse.java
- src/figvalidationservice/src/test/java/ca/bc/gov/open/pssg/rsbc/dps/figvalidationservice/facility/FacilityControllerTest.java
- src/figvalidationservice/src/test/java/ca/bc/gov/open/pssg/rsbc/dps/figvalidationservice/facility/FacilityServiceImplTest.java
- [DPSIM-124](https://justice.gov.bc.ca/jira/browse/DPSIM-124) - As the FIGARO Validation Service, I can validate facility party
Locally connected to ORDS
this PR fixes jira ticket: **DPSIM-124**
> Added Validate facility Service

- src/figvalidationservice/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/figvalidationservice/facility/ValidateFacilityPartyResponse.java
change the configuration for the object based on ORDS behavior
Running locally
> fixed issue with json non empty

- src/figvalidationservice/figcrpords.yaml
- src/figvalidationservice/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/figvalidationservice/FigaroValidation.java
- src/figvalidationservice/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/figvalidationservice/FigaroValidationImpl.java
- src/figvalidationservice/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/figvalidationservice/applicant/ApplicantController.java
- src/figvalidationservice/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/figvalidationservice/applicant/ApplicantService.java
- src/figvalidationservice/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/figvalidationservice/applicant/ApplicantServiceImpl.java
- src/figvalidationservice/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/figvalidationservice/applicant/types/ValidateApplicantForSharingRequest.java
- src/figvalidationservice/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/figvalidationservice/applicant/types/ValidateApplicantForSharingResponse.java
- src/figvalidationservice/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/figvalidationservice/configuration/OrdsFigcrConfig.java
- src/figvalidationservice/src/test/java/ca/bc/gov/open/pssg/rsbc/dps/figvalidationservice/applicant/ApplicantControllerValidateApplicantForSharingTest.java
- src/figvalidationservice/src/test/java/ca/bc/gov/open/pssg/rsbc/dps/figvalidationservice/applicant/ApplicantServiceValidateApplicantForSharingTest.java
- Add unit test for applicant for sharing
- Refactor controller and service to be in the applicant namespace
Locally connected to ORDS
> Refactored ApplicantForSharing endpoint

- .gitignore
- src/pom.xml
- added jacoco plugin to generate code coverage report
running mvn test
> Added jacoco code coverage pluggin

- Jenkinsfile
Moving sonarscan stage to post deployment
Testing will be completed in Jenkins
> moved sonarscan to after deploy stage

- src/figvalidationservice/figcrpords.yaml
- src/figvalidationservice/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/figvalidationservice/org/OrgController.java
- src/figvalidationservice/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/figvalidationservice/org/OrgService.java
- src/figvalidationservice/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/figvalidationservice/org/OrgServiceImpl.java
- src/figvalidationservice/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/figvalidationservice/org/ValidateOrgPartyContactPersonResponse.java
- src/figvalidationservice/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/figvalidationservice/org/ValidateOrgPartyRequest.java
- src/figvalidationservice/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/figvalidationservice/org/ValidateOrgPartyResponse.java
- src/figvalidationservice/src/test/java/ca/bc/gov/open/pssg/rsbc/dps/figvalidationservice/org/OrgControllerTest.java
- src/figvalidationservice/src/test/java/ca/bc/gov/open/pssg/rsbc/dps/figvalidationservice/org/OrgServiceImplTest.java
Create the ValidateOrgParty endpoint / controller
> DPSIM-137-ValidateOrgParty 

- Jenkinsfile
Making changes to the sonar stages. Used the wrong documentation to setup stages, not using steps previously.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
> made changes to include steps in the jenkins for sonarqube stages

- Jenkinsfile
Added bracket to sonar stage that was missing.
Tested live in jenkins previously.
> added missing bracket

- src/paymentservice/pom.xml
- Remove Parent Pm from payment service
Locally running mvn install
> Removed Parent Pom from payment service

- README.md
- docker-compose.yml
[DPSIM-202](https://justice.gov.bc.ca/jira/browse/DPSIM-202) - Add rabbitmq to docker
Running on docker
this PR fixes jira ticket: **DPSIM-202**
> Added rabbitMq for docker

- openshift/templates/fig-validation-service.bc.yaml
- src/openshift.dockerfile
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
> Changing references to use toolspace as central repo

- src/dpsnotificationservice/pom.xml
- src/dpsnotificationservice/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsnotificationservice/Keys.java
- src/dpsnotificationservice/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsnotificationservice/OutputNotificationEndpoint.java
- src/dpsnotificationservice/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsnotificationservice/messaging/RabbitMqConfiguration.java
- src/dpsnotificationservice/src/main/resources/application.properties
- src/dpsnotificationservice/src/test/java/ca/bc/gov/open/pssg/rsbc/dps/dpsnotificationservice/OutputNotificationEndpointTest.java
- [DPSIM-203](https://justice.gov.bc.ca/jira/DPSIM-203) - Push message to appropriate queue
Unit tests + running on docker
this PR fixes jira ticket: **DPSIM-203**
> Added function to send message to queue

- openshift/pipelines/pipeline-build-template.yaml
@ChrisHoban Deserves the credit for this file. 
Master pipeline yaml file that is sanitized.
Intended uses are for importing directly into openshift. Ensure that development on this file is not pushed into the repo unless this file is re-named and committed on a per service basis.
@ChrisHoban tested this in a sandbox for the payment service before pushing up.
> added sanitized master pipeline

- src/dpsnotificationservice/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsnotificationservice/OutputNotificationEndpoint.java
- src/dpsnotificationservice/src/main/resources/outputNotification.xsd
- src/dpsnotificationservice/src/test/java/ca/bc/gov/open/pssg/rsbc/dps/dpsnotificationservice/OutputNotificationEndpointTest.java
- added restriction to xml for VIPS // CRRP
> Restrict notification service to accept VIPS and CRRC

- README.md
- docker-compose.yml
- src/dpsnotificationservice/pom.xml
- src/dpsnotificationservice/src/main/resources/application.properties
- [DPSIM-206](https://justice.gov.bc.ca/jira/browse/DPSIM-206) - Add health checks for notification service
this PR fixes jira ticket: **DPSIM-206**
> Added actuator and changed port on docker

- README.md
- docker-compose.yml
- src/service-api/conf/nginx.conf
- [DPSIM-207](https://justice.gov.bc.ca/jira/browse/DPSIM-207) - Add soap service route to nginx
Tested on docker locally
this PR fixes jira ticket: **DPSIM-207**
> Added soap service to nginx config

- README.md
- docker-compose.yml
- src/pom.xml
- src/vips-notification-worker/.gitignore
- src/vips-notification-worker/README.md
- src/vips-notification-worker/pom.xml
- src/vips-notification-worker/src/main/java/ca/bc/gov/open/pssg/rsbc/vips/notification/worker/VipsNotificationWorkerApplication.java
- src/vips-notification-worker/src/main/resources/application.properties
- src/vips-notification-worker/src/test/java/ca/bc/gov/open/pssg/rsbc/vips/notification/worker/VipsNotificationWorkerApplicationTests.java
- [DPSIM-208](https://justice.gov.bc.ca/jira/browse/DPSIM-208) - Create basic app fore the VIPS worker
this PR fixes jira ticket: **DPSIM-208**
> Added new base app for vips worker

- src/crrp-notification-worker/src/main/java/ca/bc/gov/open/pssg/rsbc/crrp/notification/worker/Keys.java
- src/crrp-notification-worker/src/main/java/ca/bc/gov/open/pssg/rsbc/crrp/notification/worker/OutputNotificationConsumer.java
- src/crrp-notification-worker/src/main/java/ca/bc/gov/open/pssg/rsbc/crrp/notification/worker/messaging/RabbitMqConfiguration.java
> added javadoc

- docker-compose.yml
- src/libs/figaro-ords-client/figcrpords.yaml
- src/vips-notification-worker/pom.xml
- src/vips-notification-worker/src/main/java/ca/bc/gov/open/pssg/rsbc/vips/notification/worker/ords/client/OrdsFigcrConfig.java
- src/vips-notification-worker/src/main/java/ca/bc/gov/open/pssg/rsbc/vips/notification/worker/ords/client/OrdsFigcrProperties.java
- src/vips-notification-worker/src/main/resources/application.properties
- added the figaro ords client to vips
this PR fixes jira ticket: **DPSIM-209**
> added figaro client to vips client

- tests/postman/DPS-Payment-Service.postman_collection.json
- tests/postman/dps-dev-env.postman_environment.json
- tests/postman/dps-local-env.postman_environment.json
1. Modified payment service collection tests
2. Created local and open shift dev environment variables
3. Removed the previous dps-env environment file
4. Separated payment service collections from 'DPS-Service-Api' collections
Tested the collections on localhost and dev.
this PR is part of jira ticket: **193**
> Modified payment service collections and created local/dev env

- tests/springboot-ewsconntest/.gitignore
- tests/springboot-ewsconntest/README.md
- tests/springboot-ewsconntest/mvnw
- tests/springboot-ewsconntest/mvnw.cmd
- tests/springboot-ewsconntest/pom.xml
- tests/springboot-ewsconntest/src/main/java/my/pkg/name/EWSAutodiscoverAPI.java
- tests/springboot-ewsconntest/src/main/java/my/pkg/name/EWSController.java
- tests/springboot-ewsconntest/src/main/java/my/pkg/name/SpringbootEwsconntestApplication.java
- tests/springboot-ewsconntest/src/main/resources/application.properties
- tests/springboot-ewsconntest/src/test/java/my/pkg/name/SpringbootEwsconntestApplicationTests.java
Outlook client to fetch a filtered set of email from a user's account. See the main controller for example. 
Note: It ain't perfect but not expected to be!
Note: Alex expected this code to be added to the repo for reference in email poller,
Hasn't really other then with my account, smillar.
this PR fixes jira ticket: **n/a**
> Added outlook test - Demonstrates how to interact with outlook exchange server. 

- tests/postman/DPS-Service-Api.postman_collection.json
- a new request in postman to test the notification service
Locally using postman
> Added test for notification service

- src/pom.xml
this PR includes the following change:
- adding the new vips-client to the parent pom.xml
Locally using intellij
> Adding vips client to parent pom file

- src/vips-notification-worker/src/main/java/ca/bc/gov/open/pssg/rsbc/vips/notification/worker/OutputNotificationConsumer.java
- src/vips-notification-worker/src/main/java/ca/bc/gov/open/pssg/rsbc/vips/notification/worker/sftp/SftpProperties.java
- src/vips-notification-worker/src/main/resources/application.properties
- src/vips-notification-worker/src/test/java/ca/bc/gov/open/pssg/rsbc/vips/notification/worker/OutputNotificationConsumerTest.java
- [DPSIM-225](https://justice.gov.bc.ca/jira/secure/RapidBoard.jspa?rapidView=3601&view=detail&selectedIssue=DPSIM-225) - configure path to the sftp server
this PR fixes jira ticket: **DPSIM-225**
> added support to download the file

- src/spd-notification-worker/pom.xml
- src/spd-notification-worker/src/main/resources/kofax.spd.metadata.xsd
- Adding the metadata for the kofax service
Locally using intellij
> Adding the metadata definition for kofax

- src/libs/dps-sftp-starter/pom.xml
- src/libs/dps-sftp-starter/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/sftp/starter/AutoConfiguration.java
- src/libs/dps-sftp-starter/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/sftp/starter/DpsSftpException.java
- src/libs/dps-sftp-starter/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/sftp/starter/SftpProperties.java
- src/libs/dps-sftp-starter/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/sftp/starter/SftpService.java
- src/libs/dps-sftp-starter/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/sftp/starter/SftpServiceImpl.java
- src/libs/dps-sftp-starter/src/main/resources/META-INF/spring.factories
- src/libs/dps-sftp-starter/src/test/java/SftpServiceImplTest.java
- src/pom.xml
- src/vips-notification-worker/pom.xml
- src/vips-notification-worker/src/main/java/ca/bc/gov/open/pssg/rsbc/vips/notification/worker/OutputNotificationConsumer.java
- src/vips-notification-worker/src/test/java/ca/bc/gov/open/pssg/rsbc/vips/notification/worker/OutputNotificationConsumerTest.java
- Extract sftp service to a spring boot starter
Locally using docker
> Externalized sftp server

- src/spd-notification-worker/pom.xml
- src/spd-notification-worker/src/main/resources/application.properties
- Add the SFTP starter service to SPD
no tests
> Adding sftp service to spd worker

- README.md
- tests/postman/DPS-Payment-Service.postman_collection.json
- tests/postman/DPS-Service-Api-Fig.postman_collection.json
- tests/postman/DPS-Service-Api.postman_collection.json
- tests/postman/fig-locate-matching-applicants-datafile.json
- tests/postman/get-valid-open-dfcm-case-datafile.json
Created tests and data file for 'Located matching applicants' fig service endpoint. Updated README and fixed a typo from the previous commit. Replaced 'function' keyword with fat arrows in the code for all collection tests and added an env file with DPS service gateway url to run payment service tests.
Ran tests locally on the Postman app and in CLI with Newman.
this PR is part of  jira ticket: ** # 196**
> Postman test collections 3

- tests/postman/DPS-Service-Api-Fig.postman_collection.json
- tests/postman/fig-validate-applicant-service.json
Created a postman collection folder and data file to validate applicant service endpoint.
Tested on postman app and Newman CLI tool
this PR is part of the jira ticket: **196**
> Tests data file for validate applicant service endpoint

- src/libs/dps-files/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/files/FileInfo.java
- src/libs/dps-files/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/files/FileService.java
- src/libs/dps-files/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/files/FileServiceImpl.java
- src/libs/dps-files/src/test/java/ca/bc/gov/open/pssg/rsbc/dps/files/FileInfoTest.java
- src/libs/dps-files/src/test/java/ca/bc/gov/open/pssg/rsbc/dps/files/FileServiceImplTest.java
- src/libs/dps-notification/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/files/notification/OutputNotificationMessage.java
- src/libs/dps-sftp-starter/pom.xml
- src/libs/dps-sftp-starter/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/sftp/starter/SftpService.java
- src/libs/dps-sftp-starter/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/sftp/starter/SftpServiceImpl.java
- src/libs/dps-sftp-starter/src/test/java/SftpServiceImplTest.java
- src/vips-notification-worker/src/main/java/ca/bc/gov/open/pssg/rsbc/vips/notification/worker/Keys.java
- src/vips-notification-worker/src/main/java/ca/bc/gov/open/pssg/rsbc/vips/notification/worker/OutputNotificationConsumer.java
- src/vips-notification-worker/src/main/java/ca/bc/gov/open/pssg/rsbc/vips/notification/worker/document/DocumentServiceImpl.java
- src/vips-notification-worker/src/main/java/ca/bc/gov/open/pssg/rsbc/vips/notification/worker/document/VipsDocumentResponse.java
- src/vips-notification-worker/src/test/java/ca/bc/gov/open/pssg/rsbc/vips/notification/worker/OutputNotificationConsumerTest.java
- Refactoring of the vips consumer
Running locally on docker
> refactoring consumer

- docker-compose.yml
- src/paymentservice/src/main/resources/application.properties
- change default port to 8080 for the payment service
Locally
> Change port to run on 8080

- docker-compose.yml
- src/paymentservice/pom.xml
This is a temp fix to use maven openshift profile when building the app on openshift
> temporary change profile to openshift

- src/paymentservice/src/main/resources/logback-access.xml
- change dps-logs to dps-access-logs source for access logs
no test
> change source for access logs

- src/paymentservice/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/paymentservice/BamboraClientImpl.java
- Clean up of unused code in the payment service
Locally using docker
> Removed unused code

- docker-compose.yml
- src/figaro-validation-service/pom.xml
- change the splunk profile to openshift profile (temp change)
Locally
> Add temp openshift profile

- src/pom.xml
- Adding all libs to the libs profile on the main `POM.xml` file.
no test
> Adding all libs to libs profile

- src/figaro-validation-service/pom.xml
- src/figaro-validation-service/src/main/resources/application.properties
- src/figaro-validation-service/src/main/resources/logback-access.xml
- src/figaro-validation-service/src/main/resources/logback-splunk.xml
- Includes the access logs for the figaro-validation-service
running locally.
> enabling access logs on figaro validation service

- src/libs/dfcms-ords-client/dfcmsords.yaml
- src/libs/dfcms-ords-client/pom.xml
- src/libs/dfcms-ords-client/src/main/java/ca/bc/gov/open/pssg/rsbc/dfcms/ords/client/DfcmsOrdsClientConstants.java
- src/libs/dfcms-ords-client/src/main/java/ca/bc/gov/open/pssg/rsbc/dfcms/ords/client/dfcmscase/CaseSequenceNumberResponse.java
- src/libs/dfcms-ords-client/src/main/java/ca/bc/gov/open/pssg/rsbc/dfcms/ords/client/dfcmscase/CaseService.java
- src/libs/dfcms-ords-client/src/main/java/ca/bc/gov/open/pssg/rsbc/dfcms/ords/client/dfcmscase/CaseServiceImpl.java
- src/libs/dfcms-ords-client/src/main/java/ca/bc/gov/open/pssg/rsbc/dfcms/ords/client/health/HealthResponse.java
- src/libs/dfcms-ords-client/src/main/java/ca/bc/gov/open/pssg/rsbc/dfcms/ords/client/health/HealthService.java
- src/libs/dfcms-ords-client/src/main/java/ca/bc/gov/open/pssg/rsbc/dfcms/ords/client/health/HealthServiceImpl.java
- src/libs/dfcms-ords-client/src/test/java/ca/bc/gov/open/pssg/rsbc/dfcms/ords/client/dfcmscase/CaseServiceImplTest.java
- src/libs/dfcms-ords-client/src/test/java/ca/bc/gov/open/pssg/rsbc/dfcms/ords/client/health/HealthServiceImplTest.java
Create the Case and Health Service
> Create the DFCMS-ORDS-CLIENT

- src/paymentservice/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/paymentservice/BamboraClientImpl.java
- src/paymentservice/src/test/java/ca/bc/gov/open/pssg/rsbc/dps/paymentservice/BamboraClientImplTest.java
- src/paymentservice/src/test/java/ca/bc/gov/open/pssg/rsbc/dps/paymentservice/PaymentserviceApplicationTests.java
> Fix bug with Approve declined

- src/paymentservice/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/paymentservice/BamboraClientImpl.java
- src/paymentservice/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/paymentservice/PaymentClient.java
- src/paymentservice/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/paymentservice/controller/CalculateSinglePaymentController.java
- src/paymentservice/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/paymentservice/types/SinglePaymentRequest.java
- src/paymentservice/src/test/java/ca/bc/gov/open/pssg/rsbc/dps/paymentservice/BamboraClientImplTest.java
- Refactor of the payment service
Running unit tests
> Refactor BamboraClient

- src/paymentservice/README.md
- src/paymentservice/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/paymentservice/BamboraClientImpl.java
- src/paymentservice/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/paymentservice/PaymentClient.java
- src/paymentservice/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/paymentservice/configuration/BamboraConfig.java
- src/paymentservice/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/paymentservice/configuration/BamboraProperties.java
- src/paymentservice/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/paymentservice/controller/CalculateSinglePaymentController.java
- src/paymentservice/src/main/resources/application.properties
- src/paymentservice/src/test/java/ca/bc/gov/open/pssg/rsbc/dps/paymentservice/BamboraClientImplTest.java
- src/paymentservice/src/test/java/ca/bc/gov/open/pssg/rsbc/dps/paymentservice/CalculateSinglePaymentControllerTest.java
this PR includes the following changes:
- [DPSIM-311](https://justice.gov.bc.ca/jira/browse/DPSIM-311) - fix for the timezone
Running the service locally
this PR fixes jira ticket: **DPSIM-311**
> Add a new parameter for controlling timezon

- src/paymentservice/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/paymentservice/BamboraClientImpl.java
- fix issue with timezone.
Locally
> fix issue with timezone

- src/paymentservice/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/paymentservice/BamboraClientImpl.java
- src/paymentservice/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/paymentservice/PaymentClient.java
- src/paymentservice/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/paymentservice/PaymentServiceConstants.java
- src/paymentservice/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/paymentservice/controller/CalculateSinglePaymentController.java
- src/paymentservice/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/paymentservice/types/SinglePaymentRequest.java
- fixing sonarQube bugs
Running unit tests
> Fix sonar bugs

- src/libs/dfcms-ords-client/src/main/java/ca/bc/gov/open/pssg/rsbc/dfcms/ords/client/dfcmscase/CaseServiceImpl.java
- src/libs/dps-sftp-starter/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/sftp/starter/SftpServiceImpl.java
- src/libs/figaro-ords-client/src/main/java/ca/bc/gov/open/pssg/rsbc/figaro/ords/client/applicant/ApplicantServiceImpl.java
- src/libs/figaro-ords-client/src/main/java/ca/bc/gov/open/pssg/rsbc/figaro/ords/client/document/DocumentServiceImpl.java
- src/libs/figaro-ords-client/src/main/java/ca/bc/gov/open/pssg/rsbc/figaro/ords/client/facility/FacilityServiceImpl.java
- src/libs/figaro-ords-client/src/main/java/ca/bc/gov/open/pssg/rsbc/figaro/ords/client/organization/OrganizationServiceImpl.java
- src/libs/vips-ords-client/src/main/java/ca/bc/gov/open/pssg/rsbc/vips/ords/client/document/DocumentServiceImpl.java
- fix all issues with printing the stacktrace by adding the exception to the logger
Running unit tests.
> Fixing issue with stacktrace

- src/libs/dps-sftp-starter/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/sftp/starter/SftpServiceImpl.java
This PR includes the following changes
- Apply try-with pattern for closable resources
running a test locally with the services.
> apply sonarqube fix

- src/libs/figaro-ords-client/src/main/java/ca/bc/gov/open/pssg/rsbc/figaro/ords/client/document/DpsDataIntoFigaroRequestBody.java
- fix empty constructor
running unit tests
> fixed empty constructor

- src/dps-validation-service/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsvalidationservice/dfcms/ValidationController.java
- src/dps-validation-service/src/test/java/ca/bc/gov/open/pssg/rsbc/dps/dpsvalidationservice/dfcms/ValidationControllerTest.java
- src/figaro-validation-service/src/test/java/ca/bc/gov/open/pssg/rsbc/dps/figvalidationservice/applicant/ApplicantControllerLocateMatchingApplicantTest.java
- src/figaro-validation-service/src/test/java/ca/bc/gov/open/pssg/rsbc/dps/figvalidationservice/applicant/ApplicantControllerValidateApplPartyIdTest.java
- src/figaro-validation-service/src/test/java/ca/bc/gov/open/pssg/rsbc/dps/figvalidationservice/applicant/ApplicantControllerValidateApplicantForSharingTest.java
- src/figaro-validation-service/src/test/java/ca/bc/gov/open/pssg/rsbc/dps/figvalidationservice/applicant/ApplicantControllerValidateOrgApplicantTest.java
- src/figaro-validation-service/src/test/java/ca/bc/gov/open/pssg/rsbc/dps/figvalidationservice/facility/FacilityControllerTest.java
- src/figaro-validation-service/src/test/java/ca/bc/gov/open/pssg/rsbc/dps/figvalidationservice/org/OrganizationControllerTest.java
- src/libs/dfcms-ords-client/src/main/java/ca/bc/gov/open/pssg/rsbc/dfcms/ords/client/dfcmscase/CaseSequenceNumberResponse.java
- src/libs/dfcms-ords-client/src/main/java/ca/bc/gov/open/pssg/rsbc/dfcms/ords/client/dfcmscase/CaseServiceImpl.java
- src/libs/figaro-ords-client/src/main/java/ca/bc/gov/open/pssg/rsbc/figaro/ords/client/applicant/ApplicantServiceImpl.java
- src/libs/figaro-ords-client/src/main/java/ca/bc/gov/open/pssg/rsbc/figaro/ords/client/applicant/types/LocateMatchingApplicantsResponse.java
- src/libs/figaro-ords-client/src/main/java/ca/bc/gov/open/pssg/rsbc/figaro/ords/client/applicant/types/ValidateApplicantForSharingResponse.java
- src/libs/figaro-ords-client/src/main/java/ca/bc/gov/open/pssg/rsbc/figaro/ords/client/applicant/types/ValidateApplicantPartyIdResponse.java
- src/libs/figaro-ords-client/src/main/java/ca/bc/gov/open/pssg/rsbc/figaro/ords/client/applicant/types/ValidateOrgApplicantServiceResponse.java
- src/libs/figaro-ords-client/src/main/java/ca/bc/gov/open/pssg/rsbc/figaro/ords/client/document/DocumentServiceImpl.java
- src/libs/figaro-ords-client/src/main/java/ca/bc/gov/open/pssg/rsbc/figaro/ords/client/document/DpsDataIntoFigaroResponse.java
- src/libs/figaro-ords-client/src/main/java/ca/bc/gov/open/pssg/rsbc/figaro/ords/client/document/DpsDocumentResponse.java
- src/libs/figaro-ords-client/src/main/java/ca/bc/gov/open/pssg/rsbc/figaro/ords/client/facility/FacilityServiceImpl.java
- src/libs/figaro-ords-client/src/main/java/ca/bc/gov/open/pssg/rsbc/figaro/ords/client/facility/ValidateFacilityPartyResponse.java
- src/libs/figaro-ords-client/src/main/java/ca/bc/gov/open/pssg/rsbc/figaro/ords/client/organization/OrganizationServiceImpl.java
- src/libs/figaro-ords-client/src/main/java/ca/bc/gov/open/pssg/rsbc/figaro/ords/client/organization/ValidateOrgDrawDownBalanceResponse.java
- src/libs/figaro-ords-client/src/main/java/ca/bc/gov/open/pssg/rsbc/figaro/ords/client/organization/ValidateOrgPartyResponse.java
- src/libs/vips-ords-client/src/main/java/ca/bc/gov/open/pssg/rsbc/vips/ords/client/document/DocumentServiceImpl.java
- src/libs/vips-ords-client/src/main/java/ca/bc/gov/open/pssg/rsbc/vips/ords/client/document/VipsDocumentResponse.java
- src/spd-notification-worker/src/test/java/ca/bc/gov/open/pssg/rsbc/spd/notification/worker/OutputNotificationConsumerTest.java
- src/vips-notification-worker/src/test/java/ca/bc/gov/open/pssg/rsbc/vips/notification/worker/OutputNotificationConsumerTest.java
- java renaming for ErrorResponse and SuccessResponse
Running all unit tests.
> Renamed ErrorResponse and SuccessResponse

- README.md
- docs/payment-service.swagger.yml
- adding swagger as part of the documentation.
> Adding payment service swagger

- src/paymentservice/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/paymentservice/controller/CalculateSinglePaymentController.java
> Adding invoice id to MDC

- src/dps-validation-service/pom.xml
- src/figaro-validation-service/pom.xml
- src/pom.xml
- fix missing spring boot build
Running locally using `java -jar`
> fixing pom files

- src/dps-email-poller/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailpoller/email/DpsEmailException.java
- src/dps-email-poller/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailpoller/email/EmailConfig.java
- src/dps-email-poller/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailpoller/email/EmailService.java
- src/dps-email-poller/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailpoller/email/EmailServiceImpl.java
- src/dps-email-poller/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailpoller/messaging/MessagingService.java
- src/dps-email-poller/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailpoller/scheduler/EmailPoller.java
- Prepare interface for the dps email service.
no test
> Prepared Dps Mail interfaces

- tests/postman/DPS-Service-Api-Fig.postman_collection.json
- tests/postman/fig-validate-facility-party-datafile.json
- tests/postman/fig-validate-org-draw-down-balance-datafile.json
PR includes test data files for 'validateFacilityParty' and 'validateOrgDrawDownBalance' and updated collection file.
Tested on the postman app locally.
this PR is part of jira ticket: #321
> Validate facility party

- src/dps-validation-service/pom.xml
- update parent pom for the dps validation service
Locally running the app
> Changing parent pom to spring by cdpo

- src/dps-email-poller/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailpoller/scheduler/EmailPoller.java
- src/dps-email-poller/src/test/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailpoller/EmailPollerJunkRemovalTest.java
- src/dps-email-poller/src/test/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailpoller/EmailPollerPollForEmails.java
[https://justice.gov.bc.ca/jira/browse/DPSIM-328](https://justice.gov.bc.ca/jira/browse/DPSIM-328) - Complete implementation of getEmailPoller
Unit Tests
> adding poller

- tests/postman/DPS-Payment-Service.postman_collection.json
- tests/postman/DPS-Service-Api-Fig.postman_collection.json
- tests/postman/fig-validate-org-draw-down-balance-datafile.json
PR includes updated tests for 'validateOrgDrawDownBalance' endpoint and updated collection files.
This has been tested on postman collection runner locally.
this PR fixes jira ticket: https://justice.gov.bc.ca/jira/browse/DPSIM-196
> Updated tests for draw down balance and collections

- src/dps-notification-service/pom.xml
- src/pom.xml
This is a PR for the following:
- Remove all spring boot deps in the main pom.xml
Locally running tests
> Clean up of main pom by removing all spring boot deps

- src/paymentservice/src/main/resources/logback-access.xml
This is a PR to test the raw format for the access logs.
> Adding raw logs to splunk access logs

- src/paymentservice/src/main/resources/logback-access.xml
Reverse change for the payment service access logs
> Reversing change on raw logs

- .github/workflows/maven-sonar.yml
- src/pom.xml
- Refactoring maven profiles
running mvn commands
> setting up profiles

- src/figaro-validation-service/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/figvalidationservice/facility/FacilityController.java
- [DPSIM-321](https://justice.gov.bc.ca/jira/browse/DPSIM-321) fix issue with case.
Running locally
this PR fixes jira ticket: **DPSIM-321**
> Changed case on facilitySubName

- src/figaro-validation-service/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/figvalidationservice/applicant/ApplicantController.java
Fixing issues identified by sonar
Unit tests executed and Postman tests
> Fix Identified Issues

- .github/workflows/maven-sonar.yml
- .github/workflows/maven-test-pr.yml
- README.md
Adding caching for git actions
> Caching deps on git action

- src/dps-email-poller/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailpoller/messaging/EmailInfoMessage.java
- src/dps-email-poller/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailpoller/scheduler/EmailPoller.java
Fixing issues identified by sonar scan
Unit tests
> Fixing Sonar Issues

- src/dps-validation-service/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsvalidationservice/dfcms/ValidationController.java
Fix an issue with the case on DFCMS
unit tests
> fix case on the getDfcmCase

- src/libs/dfcms-ords-client/src/main/java/ca/bc/gov/open/pssg/rsbc/dfcms/ords/client/health/HealthResponse.java
- src/libs/dfcms-ords-client/src/main/java/ca/bc/gov/open/pssg/rsbc/dfcms/ords/client/health/HealthServiceImpl.java
Fix naming convention
Unit tests
> Fixing Naming Rule

- src/libs/figaro-ords-client/src/main/java/ca/bc/gov/open/pssg/rsbc/figaro/ords/client/health/HealthResponse.java
- src/libs/figaro-ords-client/src/main/java/ca/bc/gov/open/pssg/rsbc/figaro/ords/client/health/HealthServiceImpl.java
Fix naming convention
Unit tests
> Fixing Naming Rule 2

- src/dps-notification-service/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsnotificationservice/OutputNotificationEndpoint.java
> Sonar Fixes

- src/dps-email-poller/pom.xml
- src/dps-email-poller/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailpoller/email/DpsEmailContent.java
- src/dps-email-poller/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailpoller/email/DpsEmailParser.java
- src/dps-email-poller/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailpoller/email/DpsEmailParserImpl.java
- src/dps-email-poller/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailpoller/email/DpsMetadataMapper.java
- src/dps-email-poller/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailpoller/email/DpsMetadataMapperImpl.java
- src/dps-email-poller/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailpoller/email/EmailConfig.java
- src/dps-email-poller/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailpoller/messaging/MessagingService.java
- src/dps-email-poller/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailpoller/messaging/MessagingServiceImpl.java
- src/dps-email-poller/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailpoller/messaging/RabbitMqConfig.java
- src/dps-email-poller/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailpoller/scheduler/EmailPoller.java
- src/dps-email-poller/src/test/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailpoller/email/DpsEmailMapperImplTest.java
- src/dps-email-poller/src/test/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailpoller/email/DpsEmailParserImplTest.java
- src/dps-email-poller/src/test/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailpoller/email/TestKey.java
- src/dps-email-poller/src/test/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailpoller/messaging/MessagingServiceImplTest.java
- src/dps-email-poller/src/test/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailpoller/scheduler/EmailPollerJunkRemovalTest.java
- src/dps-email-poller/src/test/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailpoller/scheduler/EmailPollerPollForEmailsTest.java
- src/libs/dps-commons/pom.xml
- src/libs/dps-commons/src/main/java/ca/bc/gov/open/pssg/rsbc/DpsMetadata.java
- src/pom.xml
- src/report/pom.xml
this PR includes the following proposed changes:
- [DPSIM-360](https://justice.gov.bc.ca/jira/browse/DPSIM-360) - Generate model for the metadata document
Locally using app + unit tests
this PR fixes jira ticket: **DPSIM-360**
> Adding support to read dps metadata

- src/dps-validation-service/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsvalidationservice/dfcms/ValidationController.java
- src/dps-validation-service/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsvalidationservice/health/HealthCheck.java
- src/dps-validation-service/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsvalidationservice/health/HealthResponse.java
- src/dps-validation-service/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsvalidationservice/health/HealthServiceImpl.java
Fixing issues identified by sonar
Unit tests and light postman testing
> DPS Validation Service Sonar Issues

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.md
> Adding contributing and code of conduct

- src/dps-email-poller/pom.xml
- src/dps-notification-service/pom.xml
- src/dps-payment-service/pom.xml
- src/dps-validation-service/pom.xml
- src/figaro-validation-service/pom.xml
- src/libs/dfcms-ords-client/pom.xml
- src/libs/dps-commons/pom.xml
- src/libs/dps-files/pom.xml
- src/libs/dps-messaging-starter/pom.xml
- src/libs/dps-notification/pom.xml
- src/libs/dps-sftp-starter/pom.xml
- src/libs/figaro-ords-client/pom.xml
- src/libs/vips-ords-client/pom.xml
- src/pom.xml
- src/report/pom.xml
- src/spd-notification-worker/pom.xml
- src/vips-notification-worker/pom.xml
Version upgrade to 0.2.0-SNAPSHOT
> updated version to 0.2.0-SNAPSHOT

- src/dps-email-poller/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailpoller/configuration/ExchangeConfig.java
- fix known bug on sonarqube for disposable resource
Tested with sonarlint
> Added suppressed warning for known bug

- src/dps-validation-service/src/test/java/ca/bc/gov/open/pssg/rsbc/dps/dpsvalidationservice/DpsValidationserviceApplicationTests.java
- src/figaro-validation-service/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/figvalidationservice/applicant/ApplicantController.java
- src/figaro-validation-service/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/figvalidationservice/org/OrganizationController.java
This removes blocker
Unit test
> Sonar fixes 

- src/vips-notification-worker/src/main/java/ca/bc/gov/open/pssg/rsbc/vips/notification/worker/health/HealthCheck.java
> Fix sonar issue

- src/libs/figaro-ords-client/figcrpords.yaml
- Fix issue with auth in swagger.
locally running the app
> Fix authorization issue

- .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
- Simplified the PR template
No test required
> Refactoring pr template

- src/libs/vips-ords-client/vipsords.yaml
- fix authorization in vips swagger
locally
> updated security for endpoints

- src/figaro-validation-service/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/figvalidationservice/applicant/ApplicantController.java
- src/figaro-validation-service/src/test/java/ca/bc/gov/open/pssg/rsbc/dps/figvalidationservice/applicant/ApplicantControllerValidateOrgApplicantTest.java
- src/libs/figaro-ords-client/src/main/java/ca/bc/gov/open/pssg/rsbc/figaro/ords/client/applicant/ApplicantService.java
- src/libs/figaro-ords-client/src/main/java/ca/bc/gov/open/pssg/rsbc/figaro/ords/client/applicant/ApplicantServiceImpl.java
- src/libs/figaro-ords-client/src/main/java/ca/bc/gov/open/pssg/rsbc/figaro/ords/client/applicant/types/ValidateApplicantServiceResponse.java
- src/libs/figaro-ords-client/src/test/java/ca/bc/gov/open/pssg/rsbc/figaro/ords/client/applicant/ApplicantServiceValidateOrgTest.java
- [DPSIM-365](https://justice.gov.bc.ca/jira/browse/DPSIM-365) - DEV Figaro Service | Validate applicant service- Response property name does not match WebMethods
Running the app locally
> Fixed case and spelling of the response

- src/dps-email-poller/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailpoller/email/EmailConfig.java
- src/dps-email-poller/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailpoller/email/EmailProperties.java
- src/dps-email-poller/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailpoller/scheduler/EmailPoller.java
- src/dps-email-poller/src/main/resources/application.properties
Updating configs 
Unit test and run project locally
> Updating email configs

- tests/postman/DPS-Payment-Service.postman_collection.json
- tests/postman/DPS-Service-Api-Fig.postman_collection.json
- tests/postman/dps-dev-env.postman_environment.json
- Refactoring postman collection
Locally using newman
> Refactoring Postman

- tests/postman/DPS-Payment-Service.postman_collection.json
- fix path in the postman collection
run with newman
> fixed path in request

- src/figaro-validation-service/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/figvalidationservice/health/Liveness.java
- src/figaro-validation-service/src/main/resources/application.properties
- src/figaro-validation-service/src/test/java/ca/bc/gov/open/pssg/rsbc/dps/figvalidationservice/health/LivenessTest.java
- [FIGARO-2559](https://justice.gov.bc.ca/jira/browse/FIGARO-2559) - reduce health checks
Running the app locally.
> add liveness endpoint

- src/dps-validation-service/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsvalidationservice/health/HealthCheck.java
- src/dps-validation-service/src/test/java/ca/bc/gov/open/pssg/rsbc/dps/dpsvalidationservice/health/HealthCheckTest.java
- [DFCMS-145](https://justice.gov.bc.ca/jira/browse/DFCMS-145) - TEST | deploy DPS - DFCMS ords packages
> implemented health every 10 min

- src/figaro-validation-service/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/figvalidationservice/facility/FacilityController.java
- src/figaro-validation-service/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/figvalidationservice/org/OrganizationController.java
DPSIM-393
- bug using validateOrgParty endpoint
> To match Webmethods, the parameter 'Subname' should be 'SubName'

- src/dps-email-poller/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailpoller/email/services/EmailService.java
- src/dps-email-poller/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailpoller/email/services/EmailServiceImpl.java
- src/dps-email-poller/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailpoller/scheduler/EmailPoller.java
- src/dps-email-poller/src/test/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailpoller/email/services/EmailServiceImplTest.java
- (DPSIM-362)[https://justice.gov.bc.ca/jira/browse/DPSIM-362] - get data from the attachement
Locally + unit tests.
> Added functinality to read email attachmentt

- src/dps-email-poller/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailpoller/email/services/DpsMetadataMapper.java
- src/dps-email-poller/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailpoller/email/services/DpsMetadataMapperImpl.java
- src/dps-email-poller/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailpoller/scheduler/EmailPoller.java
- src/dps-email-poller/src/test/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailpoller/email/services/DpsEmailMapperImplTest.java
- src/dps-email-poller/src/test/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailpoller/scheduler/EmailPollerPollForEmailsTest.java
- src/libs/dps-cache-starter/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/cache/RedisStorageService.java
- src/libs/dps-cache-starter/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/cache/StorageService.java
- src/libs/dps-cache-starter/src/test/java/ca/bc/gov/open/pssg/rsbc/dps/cache/RedisStorageServiceTest.java
- src/libs/dps-commons/src/main/java/ca/bc/gov/open/pssg/rsbc/DpsFileInfo.java
- src/libs/dps-commons/src/main/java/ca/bc/gov/open/pssg/rsbc/DpsMetadata.java
- Refactoring dps email service
> Adding dps file info

- src/dps-email-poller/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailpoller/configuration/SwaggerConfig.java
- src/libs/dps-email-client/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/email/client/DpsEmailProcessedResponse.java
- Refactoring 2 issues with the email api
Running the app locally
> Refactored email api

- src/dps-email-poller/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailpoller/configuration/SwaggerConfig.java
- src/dps-email-poller/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailpoller/email/api/DpsEmailController.java
- src/dps-email-poller/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailpoller/email/api/DpsEmailProcessedRequest.java
- src/dps-email-poller/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailpoller/scheduler/EmailPoller.java
- src/dps-email-poller/src/main/resources/application.properties
- src/dps-email-poller/src/test/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailpoller/email/api/DpsEmailControllerTest.java
- src/dps-email-worker/pom.xml
- src/dps-email-worker/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailworker/DpsEmailConsumer.java
- src/dps-email-worker/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailworker/DpsEmailWorkerApplication.java
- src/dps-email-worker/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailworker/Keys.java
- src/dps-email-worker/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailworker/configuration/DpsEmailConfiguration.java
- src/dps-email-worker/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailworker/configuration/RabbitMqConfiguration.java
- src/dps-email-worker/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailworker/configuration/TenantProperties.java
- src/dps-email-worker/src/main/resources/application.properties
- src/dps-email-worker/src/test/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailworker/DpsEmailConsumerTest.java
- src/libs/dps-commons/pom.xml
- src/libs/dps-commons/src/main/java/ca/bc/gov/open/pssg/rsbc/DpsFileInfo.java
- src/libs/dps-commons/src/main/java/ca/bc/gov/open/pssg/rsbc/DpsMetadata.java
- src/libs/dps-email-client/dpsemailclient.yaml
- src/libs/dps-email-client/pom.xml
- src/libs/dps-email-client/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/email/client/DpsEmailService.java
- src/libs/dps-email-client/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/email/client/DpsEmailServiceImpl.java
- src/libs/dps-email-client/src/test/java/ca/bc/gov/open/pssg/rsbc/dps/email/client/DpsEmailServiceImplTest.java
- [DPSIM-395](https://justice.gov.bc.ca/jira/browse/DPSIM-395) - Call processed endpoint from the worker
Locally
> Implementing call back to processed endpoint

- src/dps-validation-service/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsvalidationservice/dfcms/ValidationController.java
- src/dps-validation-service/src/test/java/ca/bc/gov/open/pssg/rsbc/dps/dpsvalidationservice/dfcms/ValidationControllerTest.java
- src/libs/dfcms-ords-client/src/main/java/ca/bc/gov/open/pssg/rsbc/dfcms/ords/client/dfcmscase/CaseSequenceNumberResponse.java
https://justice.gov.bc.ca/jira/browse/DPSIM-363
Update the response property names
Update the name  of the dps service to GetValidOpenDFCMCase
> Dps Validation Service updates

- README.md
- Removed line as test for commit
- [X ] Refactoring / Documentation
NA - Document change
- [X ] My code follows the style guidelines of this project
- [X ] I have performed a self-review of my own code
- [X ] I have made corresponding changes to the documentation
- [X ] New and existing unit tests pass locally with my changes
> Removed line as test for commit

- src/dps-email-poller/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailpoller/email/services/DpsEmailParserImpl.java
- src/dps-email-poller/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailpoller/scheduler/EmailPoller.java
- src/dps-email-poller/src/main/resources/application.properties
- src/dps-email-worker/pom.xml
- src/dps-email-worker/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailworker/DpsEmailConsumer.java
- src/dps-email-worker/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailworker/configuration/DpsEmailConfig.java
- src/dps-email-worker/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailworker/configuration/DpsEmailProperties.java
- src/dps-email-worker/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailworker/configuration/FileConfig.java
- src/dps-email-worker/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailworker/configuration/RabbitMqConfig.java
- src/dps-email-worker/src/main/resources/application.properties
- src/dps-email-worker/src/test/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailworker/DpsEmailConsumerTest.java
- src/libs/dps-files/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/files/FileService.java
- src/libs/dps-files/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/files/FileServiceImpl.java
- src/libs/dps-files/src/test/java/ca/bc/gov/open/pssg/rsbc/dps/files/FileServiceImplTest.java
- src/libs/dps-sftp-starter/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/sftp/starter/SftpService.java
- src/libs/dps-sftp-starter/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/sftp/starter/SftpServiceImpl.java
- src/libs/dps-sftp-starter/src/test/java/SftpServiceImplTest.java
- [DPSIM-425](https://justice.gov.bc.ca/jira/browse/DPSIM-425) - Upload image to sftp folder
Running the app locally, connected to the mailbox and a local sftp server
> DPSIM-425 - Upload image to sftp folder

- src/dps-email-poller/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailpoller/scheduler/EmailPoller.java
- src/dps-email-poller/src/test/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailpoller/email/services/DpsEmailMapperImplTest.java
- src/dps-email-worker/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailworker/DpsEmailConsumer.java
- src/dps-email-worker/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailworker/kofax/services/ImportSessionServiceImpl.java
- src/dps-email-worker/src/test/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailworker/kofax/ImportSessionServiceImplTest.java
- src/libs/dps-commons/src/main/java/ca/bc/gov/open/pssg/rsbc/models/DpsMetadata.java
- src/libs/dps-commons/src/main/java/ca/bc/gov/open/pssg/rsbc/monitoring/MdcConstants.java
- Adding transaction id to MDC generated on reception of email
Unit Tests
> Adding Transaction Id to MDC

- src/dps-email-worker/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailworker/DpsEmailConsumer.java
- src/dps-email-worker/src/main/resources/application.properties
- src/libs/dps-bom/pom.xml
- src/libs/dps-sftp-starter/pom.xml
- src/libs/dps-sftp-starter/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/sftp/starter/AutoConfiguration.java
- src/libs/dps-sftp-starter/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/sftp/starter/SftpProperties.java
- src/spd-notification-worker/src/main/resources/application.properties
- src/vips-notification-worker/src/main/resources/application.properties
- [DPSIM-427](https://justice.gov.bc.ca/jira/browse/DPSIM-427) - enable cert authentication
No test yet cert auth will be run in openshift only, basic auth still working locally
> Adding support for cert auth

- src/dps-notification-service/README.md
- src/dps-payment-service/README.md
- Improving notification service doc
N/A
> Adding information about notification service configuration

- src/dps-email-worker/src/main/resources/application.properties
- src/spd-notification-worker/README.md
- src/spd-notification-worker/src/main/resources/application-cloud.properties
- src/spd-notification-worker/src/main/resources/application.properties
- Refactoring SPD documentation
N/A
> Adding documentation and fixing properties files

- src/spd-notification-worker/README.md
- src/spd-notification-worker/pom.xml
- src/spd-notification-worker/src/main/resources/application-splunk.properties
- src/spd-notification-worker/src/main/resources/logback-splunk.xml
- src/spd-notification-worker/src/main/resources/logback.xml
- add splunk configuration for the workers
> Adding splunk support

- src/spd-notification-worker/README.md
- src/spd-notification-worker/src/main/resources/application.properties
- aligning configuration with figaro validation service
N/A
> Setting config as figaro validation service

- src/spd-notification-worker/README.md
- src/vips-notification-worker/README.md
- src/vips-notification-worker/pom.xml
- src/vips-notification-worker/src/main/resources/application-cloud.properties
- src/vips-notification-worker/src/main/resources/application-splunk.properties
- src/vips-notification-worker/src/main/resources/application.properties
- src/vips-notification-worker/src/main/resources/logback-splunk.xml
- src/vips-notification-worker/src/main/resources/logback.xml
- Enaable splunk + configuration for VIPS
N/A
> Adding splunk + documentation

- src/dps-email-poller/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailpoller/messaging/Keys.java
- src/dps-email-poller/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailpoller/messaging/MessagingServiceImpl.java
- src/dps-email-worker/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailworker/DpsEmailConsumer.java
- src/dps-email-worker/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailworker/configuration/RabbitMqConfig.java
- src/libs/dps-messaging-starter/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/messaging/starter/AutoConfiguration.java
- src/libs/dps-messaging-starter/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/messaging/starter/DpsMessageErrorHandler.java
- src/libs/dps-messaging-starter/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/messaging/starter/DpsMessagePostProcessor.java
- src/libs/dps-messaging-starter/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/messaging/starter/DpsMessagingProperties.java
- src/libs/dps-messaging-starter/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/messaging/starter/Keys.java
- src/spd-notification-worker/src/main/java/ca/bc/gov/open/pssg/rsbc/spd/notification/worker/configuration/RabbitMqConfiguration.java
- src/vips-notification-worker/src/main/java/ca/bc/gov/open/pssg/rsbc/vips/notification/worker/configuration/RabbitMqConfiguration.java
- [DPSIM-405](https://justice.gov.bc.ca/jira/browse/DPSIM-405) - Implement guaranteed delivery using retry policy
Locally
> implement garenteed delivery

- src/libs/dfcms-ords-client/pom.xml
- src/libs/dps-bom/pom.xml
BoM Versioning Update
Updated the dfcms-ords-client project to use the dps-bom for versioning of dependencies.
Verified dependencies in maven
Ran maven tests on all projects
> Version Control Improvement

- src/libs/dps-email-client/pom.xml
- src/libs/figaro-ords-client/pom.xml
- src/libs/vips-ords-client/pom.xml
Updating libs to BoM versioning for dependencies:
- dps-email-client updated to BoM versioning for dependencies
- figaro-ords-client to BoM versioning for dependencies
- vips-ords-client to BoM versioning for dependencies
- Verifying dependencies resolving in maven
- running maven test suite.
> BoM Versioning Update

- src/dps-email-worker/pom.xml
- fix build config in email worker
Locally
> fixed build config

- src/libs/dps-sftp-starter/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/sftp/starter/AutoConfiguration.java
- src/libs/dps-sftp-starter/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/sftp/starter/JschSessionProvider.java
- src/libs/dps-sftp-starter/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/sftp/starter/SftpServiceImpl.java
- src/libs/dps-sftp-starter/src/test/java/ca/bc/gov/open/pssg/rsbc/dps/sftp/starter/JschSessionProviderTest.java
- src/libs/dps-sftp-starter/src/test/java/ca/bc/gov/open/pssg/rsbc/dps/sftp/starter/SftpServiceImplTest.java
- Refactor SFTP Session management
> Adding session provider

- src/dps-notification-service/pom.xml
- src/dps-registration-api/.gitignore
- src/dps-registration-api/pom.xml
- src/dps-registration-api/src/main/java/ca/bc/gov/pssg/rsbc/dps/dpsregistrationapi/DpsRegistrationApiApplication.java
- src/dps-registration-api/src/main/resources/application.properties
- src/dps-registration-api/src/test/java/ca/bc/gov/pssg/rsbc/dps/dpsregistrationapi/DpsRegistrationApiApplicationTests.java
- src/pom.xml
- src/report/pom.xml
- [DPSIM-451](https://justice.gov.bc.ca/jira/browse/DPSIM-451) - Create base web app
> Adding new registration api

- src/libs/dps-email-client/dpsemailclient.yaml
- src/libs/dps-email-client/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/email/client/DpsEmailServiceImpl.java
- src/libs/dps-email-client/src/test/java/ca/bc/gov/open/pssg/rsbc/dps/email/client/DpsEmailServiceImplTest.java
- fix yaml for the email poller client service.
> Refactored to use generated swagger

- src/dps-registration-api/README.md
- src/dps-registration-api/pom.xml
- src/dps-registration-api/src/main/java/ca/bc/gov/pssg/rsbc/dps/dpsregistrationapi/Keys.java
- src/dps-registration-api/src/main/java/ca/bc/gov/pssg/rsbc/dps/dpsregistrationapi/RegistrationServiceEndpoint.java
- src/dps-registration-api/src/main/java/ca/bc/gov/pssg/rsbc/dps/dpsregistrationapi/WebServiceConfig.java
- src/dps-registration-api/src/main/resources/registrationService.xsd
- src/dps-registration-api/src/main/resources/registrationservice_original.xsd
- src/dps-registration-api/src/test/java/ca/bc/gov/pssg/rsbc/dps/dpsregistrationapi/RegistrationServiceEndpointRegisterObjectTest.java
- src/dps-registration-api/src/test/java/ca/bc/gov/pssg/rsbc/dps/dpsregistrationapi/registrationServiceEndpointRegisterPackageTest.java
- [DPSIM-454](https://justice.gov.bc.ca/jira/browse/DPSIM-454) - Create fake endpoints for the register object and package
Running the service locally
> Adding fake ws endpoint for register pacakge and register object

- src/dps-registration-api/pom.xml
- src/dps-registration-api/src/main/java/ca/bc/gov/pssg/rsbc/dps/dpsregistrationapi/DateUtils.java
- src/dps-registration-api/src/main/java/ca/bc/gov/pssg/rsbc/dps/dpsregistrationapi/Keys.java
- src/dps-registration-api/src/main/java/ca/bc/gov/pssg/rsbc/dps/dpsregistrationapi/RegistrationServiceEndpoint.java
- src/dps-registration-api/src/main/resources/application.properties
- src/dps-registration-api/src/test/java/ca/bc/gov/pssg/rsbc/dps/dpsregistrationapi/RegistrationServiceEndpointRegisterObjectTest.java
- src/dps-registration-api/src/test/java/ca/bc/gov/pssg/rsbc/dps/dpsregistrationapi/registrationServiceEndpointRegisterPackageTest.java
- src/libs/otssoa-ords-client/otssoa-ords.yaml
- src/libs/otssoa-ords-client/pom.xml
- src/libs/otssoa-ords-client/src/main/java/ca/bc/gov/open/ottsoa/ords/client/AutoConfiguration.java
- src/libs/otssoa-ords-client/src/main/java/ca/bc/gov/open/ottsoa/ords/client/CreatePackageRequest.java
- src/libs/otssoa-ords-client/src/main/java/ca/bc/gov/open/ottsoa/ords/client/Keys.java
- src/libs/otssoa-ords-client/src/main/java/ca/bc/gov/open/ottsoa/ords/client/OtssoaProperties.java
- src/libs/otssoa-ords-client/src/main/java/ca/bc/gov/open/ottsoa/ords/client/OtssoaService.java
- src/libs/otssoa-ords-client/src/main/java/ca/bc/gov/open/ottsoa/ords/client/OtssoaServiceImpl.java
- src/libs/otssoa-ords-client/src/main/resources/META-INF/spring.factories
- src/libs/otssoa-ords-client/src/test/java/ca/bc/gov/open/ottsoa/ords/client/OtssoaServiceTest.java
- src/pom.xml
- src/report/pom.xml
- [DPSIM-456](https://justice.gov.bc.ca/jira/browse/DPSIM-456) - implement create package endpoint
Locally + unit tests
> Added create package implementation

- src/dps-registration-api/src/main/java/ca/bc/gov/pssg/rsbc/dps/dpsregistrationapi/Keys.java
- src/dps-registration-api/src/main/java/ca/bc/gov/pssg/rsbc/dps/dpsregistrationapi/RegistrationServiceEndpoint.java
- src/dps-registration-api/src/test/java/ca/bc/gov/pssg/rsbc/dps/dpsregistrationapi/RegistrationServiceEndpointRegisterObjectTest.java
- src/dps-registration-api/src/test/java/ca/bc/gov/pssg/rsbc/dps/dpsregistrationapi/RegistrationServiceEndpointRegisterPackageTest.java
- src/libs/otssoa-ords-client/otssoa-ords.yaml
- src/libs/otssoa-ords-client/src/main/java/ca/bc/gov/open/ottsoa/ords/client/Keys.java
- src/libs/otssoa-ords-client/src/main/java/ca/bc/gov/open/ottsoa/ords/client/OtssoaService.java
- src/libs/otssoa-ords-client/src/main/java/ca/bc/gov/open/ottsoa/ords/client/OtssoaServiceImpl.java
- src/libs/otssoa-ords-client/src/main/java/ca/bc/gov/open/ottsoa/ords/client/models/CreateObjectRequest.java
- src/libs/otssoa-ords-client/src/main/java/ca/bc/gov/open/ottsoa/ords/client/models/CreatePackageRequest.java
- src/libs/otssoa-ords-client/src/test/java/ca/bc/gov/open/ottsoa/ords/client/OtssoaServiceCreateObjectTest.java
- src/libs/otssoa-ords-client/src/test/java/ca/bc/gov/open/ottsoa/ords/client/OtssoaServiceCreatePackageTest.java
- [DPSIM-458](https://justice.gov.bc.ca/jira/browse/DPSIM-458) - Implement create object endpoints to use the database client
Local Test + unit tests
> Implemented createObjectEndpoint

- src/dps-email-worker/pom.xml
- src/dps-email-worker/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailworker/DpsEmailConsumer.java
- src/dps-email-worker/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailworker/Keys.java
- src/dps-email-worker/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailworker/registration/RegistrationConfig.java
- src/dps-email-worker/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailworker/registration/RegistrationProperties.java
- src/dps-email-worker/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailworker/registration/RegistrationService.java
- src/dps-email-worker/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailworker/registration/RegistrationServiceImpl.java
- src/dps-email-worker/src/main/resources/application.properties
- src/dps-email-worker/src/test/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailworker/DpsEmailConsumerTest.java
- src/dps-email-worker/src/test/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailworker/registration/RegistrationServiceImplTest.java
- src/dps-registration-api/src/main/java/ca/bc/gov/pssg/rsbc/dps/dpsregistrationapi/RegistrationServiceEndpoint.java
- src/dps-registration-api/src/test/java/ca/bc/gov/pssg/rsbc/dps/dpsregistrationapi/RegistrationServiceEndpointRegisterObjectTest.java
- src/dps-registration-api/src/test/java/ca/bc/gov/pssg/rsbc/dps/dpsregistrationapi/RegistrationServiceEndpointRegisterPackageTest.java
- src/libs/otssoa-ords-client/src/main/java/ca/bc/gov/open/ottsoa/ords/client/AutoConfiguration.java
- src/libs/otssoa-ords-client/src/main/java/ca/bc/gov/open/ottsoa/ords/client/OtssoaService.java
- src/libs/otssoa-ords-client/src/main/java/ca/bc/gov/open/ottsoa/ords/client/OtssoaServiceImpl.java
- src/libs/otssoa-ords-client/src/test/java/ca/bc/gov/open/ottsoa/ords/client/OtssoaServiceCreateObjectTest.java
- src/libs/otssoa-ords-client/src/test/java/ca/bc/gov/open/ottsoa/ords/client/OtssoaServiceCreatePackageTest.java
- [DPSIM-459](https://justice.gov.bc.ca/jira/browse/DPSIM-459) - Implement call to api in the worker
Locally + unit tests
> Implement call to ots database

- src/dps-validation-service/pom.xml
- src/dps-validation-service/src/main/resources/logback-access.xml
- Fixed issue with logback configuration
Running the app locally
> Adding missing logback starter lib

- src/dps-email-poller/pom.xml
- src/dps-email-worker/pom.xml
- src/dps-notification-service/pom.xml
- src/dps-payment-service/pom.xml
- src/dps-registration-api/pom.xml
- src/dps-validation-service/pom.xml
- src/figaro-validation-service/pom.xml
- src/libs/dfcms-ords-client/pom.xml
- src/libs/dps-bom/pom.xml
- src/libs/dps-cache-starter/pom.xml
- src/libs/dps-commons/pom.xml
- src/libs/dps-email-client/pom.xml
- src/libs/dps-files/pom.xml
- src/libs/dps-messaging-starter/pom.xml
- src/libs/dps-notification/pom.xml
- src/libs/dps-sftp-starter/pom.xml
- src/libs/figaro-ords-client/pom.xml
- src/libs/otssoa-ords-client/pom.xml
- src/libs/vips-ords-client/pom.xml
- src/pom.xml
- src/report/pom.xml
- src/spd-notification-worker/pom.xml
- src/vips-notification-worker/pom.xml
This Pull Request is for release **DPS Version V0.3.0**
- [DPS Validation 0.3.0](https://justice.gov.bc.ca/jira/projects/DPSIM/versions/23011)
- Figaro Validation Service
- Dps Validation service
- List all fixes here.
> Updated version to 0.3.0

- src/dps-email-poller/pom.xml
- src/dps-email-worker/pom.xml
- src/dps-notification-service/pom.xml
- src/dps-payment-service/pom.xml
- src/dps-registration-api/pom.xml
- src/dps-validation-service/pom.xml
- src/figaro-validation-service/pom.xml
- src/libs/dfcms-ords-client/pom.xml
- src/libs/dps-bom/pom.xml
- src/libs/dps-cache-starter/pom.xml
- src/libs/dps-commons/pom.xml
- src/libs/dps-email-client/pom.xml
- src/libs/dps-files/pom.xml
- src/libs/dps-messaging-starter/pom.xml
- src/libs/dps-notification/pom.xml
- src/libs/dps-sftp-starter/pom.xml
- src/libs/figaro-ords-client/pom.xml
- src/libs/otssoa-ords-client/pom.xml
- src/libs/vips-ords-client/pom.xml
- src/pom.xml
- src/report/pom.xml
- src/spd-notification-worker/pom.xml
- src/vips-notification-worker/pom.xml
This Pull Request is for release **DPS Version V0.4.0-SNAPSHOT**
> updated to 0.4.0-SNAPSHOT

- src/dps-email-worker/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailworker/registration/NoActionRegistrationService.java
- src/dps-email-worker/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailworker/registration/RegistrationConfig.java
- Fix issue with dependency injection when registration is turned off.
> Fix dependency issue by creating an empty implementation

- src/dps-email-worker/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailworker/DpsEmailConsumer.java
- src/dps-email-worker/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailworker/DpsEmailWorkerApplication.java
- src/dps-email-worker/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailworker/kofax/KofaxProperties.java
- src/dps-email-worker/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailworker/monitoring/JobConfig.java
- src/dps-email-worker/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailworker/monitoring/JobController.java
- src/dps-email-worker/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailworker/monitoring/JobResponse.java
- src/dps-email-worker/src/main/resources/application.properties
- src/dps-email-worker/src/test/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailworker/monitoring/JobControllerTest.java
- src/libs/dps-files/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/files/FileService.java
- src/libs/dps-files/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/files/FileServiceImpl.java
- src/libs/dps-files/src/test/java/ca/bc/gov/open/pssg/rsbc/dps/files/FileServiceImplTest.java
- src/libs/dps-sftp-starter/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/sftp/starter/SftpService.java
- src/libs/dps-sftp-starter/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/sftp/starter/SftpServiceImpl.java
- src/libs/dps-sftp-starter/src/test/java/ca/bc/gov/open/pssg/rsbc/dps/sftp/starter/SftpServiceImplListFileTest.java
- [DPSIM-478](https://justice.gov.bc.ca/jira/browse/DPSIM-478) - New endpoint for scheduling job
> Adding support for listing error files

- src/dps-email-worker/pom.xml
- src/dps-email-worker/src/main/resources/application-splunk.properties
- src/dps-email-worker/src/main/resources/application.properties
- src/dps-email-worker/src/main/resources/logback-access.xml
- src/dps-email-worker/src/main/resources/logback-splunk.xml
- enabling splunk logging
No Test, this only applies to openshift env
> enabling splunk + access logs

- src/dps-email-worker/src/main/resources/logback-access.xml
- src/dps-email-worker/src/main/resources/logback-splunk.xml
- fix-tenant-variable-name
N/A
> fixed tenant variable

- src/dps-email-worker/pom.xml
- src/dps-email-worker/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailworker/monitoring/JobController.java
- src/libs/dps-monitoring/pom.xml
- src/libs/dps-monitoring/src/main/java/ca/bc/gov/dps/monitoring/LoggerAction.java
- src/libs/dps-monitoring/src/main/java/ca/bc/gov/dps/monitoring/NotificationService.java
- src/pom.xml
- src/report/pom.xml
- A new notification service to log notifications
Waiting to test on openshift
> Add notification service

- src/libs/dps-monitoring/src/main/java/ca/bc/gov/dps/monitoring/NotificationService.java
- fix issue with missing key
no test
> fix scope of variables

- src/dps-email-worker/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailworker/kofax/models/BatchField.java
- src/dps-email-worker/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailworker/kofax/services/ImportSessionService.java
- src/dps-email-worker/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailworker/kofax/services/ImportSessionServiceImpl.java
- src/dps-email-worker/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailworker/monitoring/ErrorMonitoringJob.java
- src/dps-email-worker/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailworker/monitoring/JobConfig.java
- src/dps-email-worker/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailworker/monitoring/JobController.java
- src/dps-email-worker/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailworker/monitoring/MonitoringJob.java
- src/dps-email-worker/src/test/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailworker/Fakes.java
- src/dps-email-worker/src/test/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailworker/kofax/ImportSessionServiceImplTest.java
- src/dps-email-worker/src/test/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailworker/monitoring/ErrorMonitoringJobTest.java
- src/dps-email-worker/src/test/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailworker/monitoring/JobControllerTest.java
- src/libs/dps-files/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/files/FileService.java
- src/libs/dps-files/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/files/FileServiceImpl.java
- src/libs/dps-files/src/test/java/ca/bc/gov/open/pssg/rsbc/dps/files/FileServiceImplTest.java
- [DPSIM-481](https://justice.gov.bc.ca/jira/browse/DPSIM-481) implement basic error workflow
locally
> Adding logic to  handle errors

- src/dps-email-worker/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailworker/monitoring/ErrorMonitoringJob.java
- src/dps-email-worker/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailworker/monitoring/JobConfig.java
- src/dps-email-worker/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailworker/monitoring/JobController.java
- src/dps-email-worker/src/test/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailworker/monitoring/ErrorMonitoringJobTest.java
- src/libs/dps-files/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/files/FileService.java
- src/libs/dps-files/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/files/FileServiceImpl.java
- src/libs/dps-monitoring/src/main/java/ca/bc/gov/dps/monitoring/LoggerAction.java
- src/libs/dps-monitoring/src/main/java/ca/bc/gov/dps/monitoring/NotificationService.java
- src/libs/dps-monitoring/src/main/java/ca/bc/gov/dps/monitoring/SystemNotification.java
- [DPSIM-483](https://justice.gov.bc.ca/jira/browse/DPSIM-483) - implemented notification + move file to error hold dir.
> implemented notification

- openshift/jobs/dps-kofax-job.yaml
Hey @ChrisHoban this is my attempt for the cronjob, please have a look. thanks!
> adding template for email poller job

- src/dps-email-worker/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailworker/monitoring/ErrorMonitoringJob.java
- src/libs/dps-monitoring/src/main/java/ca/bc/gov/dps/monitoring/SystemNotification.java
- fix issue with transactionId
> improve notification

- src/dps-email-poller/pom.xml
- src/dps-email-poller/src/main/resources/application-splunk.properties
- src/dps-email-poller/src/main/resources/logback-access.xml
- src/dps-email-poller/src/main/resources/logback-splunk.xml
> Configure splunk for email poller

- src/dps-email-worker/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailworker/DpsEmailConsumer.java
- src/dps-email-worker/src/test/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailworker/DpsEmailConsumerTest.java
- fixed an issue with correlationId
Added unit tests
> fixed correlation id

- src/dps-email-poller/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailpoller/scheduler/EmailPoller.java
- src/dps-email-worker/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailworker/DpsEmailConsumer.java
- src/dps-email-worker/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailworker/Keys.java
- src/dps-email-worker/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailworker/monitoring/ErrorMonitoringJob.java
- src/dps-email-worker/src/test/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailworker/DpsEmailConsumerTest.java
- src/libs/dps-monitoring/pom.xml
- src/libs/dps-monitoring/src/main/java/ca/bc/gov/dps/monitoring/Assertion.java
- src/libs/dps-monitoring/src/main/java/ca/bc/gov/dps/monitoring/SystemNotification.java
- src/libs/dps-monitoring/src/test/java/ca/bc/gov/dps/monitoring/SystemNotificationTest.java
- Adding success notifications
> Refactoring system notification + adding success

- src/dps-email-poller/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailpoller/scheduler/EmailPoller.java
- add success notification for the email poller
> Adding success notification for email poller

- src/dps-email-worker/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailworker/DpsEmailConsumer.java
- src/dps-email-worker/src/test/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailworker/DpsEmailConsumerTest.java
- adding notification for email move failure
> Adding logic to inform api failure

- src/dps-registration-api/pom.xml
- src/dps-registration-api/src/main/resources/application-splunk.properties
- src/dps-registration-api/src/main/resources/logback-access.xml
- src/dps-registration-api/src/main/resources/logback-splunk.xml
- src/dps-registration-api/src/main/resources/logback.xml
- src/libs/dps-bom/pom.xml
- Adding splunk logging for registration api
> Adding splunk logging

- src/dps-registration-api/pom.xml
- src/dps-registration-api/src/main/java/ca/bc/gov/pssg/rsbc/dps/dpsregistrationapi/WebServiceConfig.java
- src/dps-registration-api/src/main/java/ca/bc/gov/pssg/rsbc/dps/dpsregistrationapi/health/MetricsService.java
- src/dps-registration-api/src/main/java/ca/bc/gov/pssg/rsbc/dps/dpsregistrationapi/health/MetricsServiceImpl.java
- src/dps-registration-api/src/main/java/ca/bc/gov/pssg/rsbc/dps/dpsregistrationapi/health/OttsoaHealthCheck.java
- src/libs/dps-bom/pom.xml
- src/libs/otssoa-ords-client/otssoa-ords.yaml
> Adding health endpoints to registration service

- src/libs/otssoa-ords-client/otssoa-ords.yaml
- enabling auth on health endpoint
> enabling auth on health endpoint

- src/dps-registration-api/pom.xml
- src/dps-registration-api/src/main/java/ca/bc/gov/pssg/rsbc/dps/dpsregistrationapi/WebServiceConfig.java
- temp fix for json parser conflict between jersey and cxf.rs
Local test only
> Commenting out heath endpoints

- src/dps-registration-api/README.md
- src/dps-registration-api/src/main/java/ca/bc/gov/pssg/rsbc/dps/dpsregistrationapi/WebServiceConfig.java
- src/dps-registration-api/src/main/java/ca/bc/gov/pssg/rsbc/dps/dpsregistrationapi/WebServiceProperties.java
- src/dps-registration-api/src/main/resources/application.properties
- Adding configuration to turn on off logging for ws
Locally
> Adding logging feature on/off

- src/dps-registration-api/src/main/java/ca/bc/gov/pssg/rsbc/dps/dpsregistrationapi/RegistrationServiceEndpoint.java
- src/dps-registration-api/src/test/java/ca/bc/gov/pssg/rsbc/dps/dpsregistrationapi/RegistrationServiceEndpointRegisterObjectTest.java
- src/hs_err_pid45616.log
- fix issue with missing object type mapping
Locally + unit tests
> Updated missing content type mapping

- src/dps-notification-service/pom.xml
- src/dps-notification-service/src/main/resources/application-splunk.properties
- src/dps-notification-service/src/main/resources/logback-access.xml
- src/dps-notification-service/src/main/resources/logback-splunk.xml
- src/dps-notification-service/src/main/resources/logback.xml
- [DPSIM-505](https://justice.gov.bc.ca/jira/browse/DPSIM-505) - adding splunk logging
N/A
> Adding support for splunk

- src/dps-notification-service/pom.xml
- src/dps-notification-service/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsnotificationservice/WebServiceConfig.java
- src/dps-notification-service/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsnotificationservice/WebServiceProperties.java
- src/dps-notification-service/src/main/resources/application.properties
- src/dps-registration-api/src/main/java/ca/bc/gov/pssg/rsbc/dps/dpsregistrationapi/WebServiceConfig.java
- [DPSIM-505](https://justice.gov.bc.ca/jira/browse/DPSIM-505) - Add splunk monitoring
Locally
> Adding logging features.

- src/dps-email-poller/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailpoller/scheduler/EmailPoller.java
- src/libs/figaro-ords-client/src/main/java/ca/bc/gov/open/pssg/rsbc/figaro/ords/client/document/DocumentService.java
- src/libs/figaro-ords-client/src/main/java/ca/bc/gov/open/pssg/rsbc/figaro/ords/client/document/DocumentServiceImpl.java
- src/libs/figaro-ords-client/src/test/java/ca/bc/gov/open/pssg/rsbc/figaro/ords/client/document/DocumentServiceImplTest.java
- src/spd-notification-worker/pom.xml
- src/spd-notification-worker/src/main/java/ca/bc/gov/open/pssg/rsbc/spd/notification/worker/Keys.java
- src/spd-notification-worker/src/main/java/ca/bc/gov/open/pssg/rsbc/spd/notification/worker/OutputNotificationConsumer.java
- src/spd-notification-worker/src/test/java/ca/bc/gov/open/pssg/rsbc/spd/notification/worker/OutputNotificationConsumerTest.java
- src/vips-notification-worker/pom.xml
- src/vips-notification-worker/src/main/java/ca/bc/gov/open/pssg/rsbc/vips/notification/worker/Keys.java
- src/vips-notification-worker/src/main/java/ca/bc/gov/open/pssg/rsbc/vips/notification/worker/OutputNotificationConsumer.java
- adding success notification for spd and vips workers
> enhancing logging for notification workers

- src/libs/dps-sftp-starter/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/sftp/starter/AutoConfiguration.java
- Allow to not check known hosts for sftp connection
> Allow to not check known hosts when value is empty

- src/dps-email-worker/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailworker/DpsEmailConsumer.java
- src/dps-email-worker/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailworker/registration/NoActionRegistrationService.java
- src/dps-email-worker/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailworker/registration/RegistrationService.java
- src/dps-email-worker/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailworker/registration/RegistrationServiceImpl.java
- src/dps-email-worker/src/test/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailworker/registration/NoActionRegistrationServiceTest.java
- src/dps-email-worker/src/test/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailworker/registration/RegistrationServiceImplTest.java
- Adding function to check if registration service is active
> Adding isActive function to the RegistrationService interface

- src/dps-email-poller/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailpoller/email/services/DpsMetadataMapperImpl.java
- src/dps-email-worker/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailworker/monitoring/ErrorMonitoringJob.java
> Adding more logs to error processing

- src/dps-email-poller/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailpoller/email/services/DpsEmailParserImpl.java
- src/dps-email-poller/src/test/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailpoller/email/TestKey.java
- src/dps-email-poller/src/test/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailpoller/email/services/DpsEmailParserImplTest.java
- [https://justice.gov.bc.ca/jira/browse/DPSIM-523](https://justice.gov.bc.ca/jira/browse/DPSIM-523)
Running unit tests locally
> Removed exception when email body is empty

- src/dps-email-poller/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailpoller/configuration/ExchangeServiceFactory.java
- src/dps-email-poller/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailpoller/email/configuration/EmailConfig.java
- src/dps-email-poller/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailpoller/email/services/EmailServiceImpl.java
- src/dps-email-poller/src/test/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailpoller/email/configuration/EmailConfigTest.java
- src/dps-email-poller/src/test/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailpoller/email/services/EmailServiceImplTest.java
- [DPSIM-524](https://justice.gov.bc.ca/jira/browse/DPSIM-524) - Receiving unauthorized after running a while
Locally the application is running fine, but needs to be tested on openshift
> Changing pattern for getting the exchangeService

- openshift/templates/jenkinsfile
- openshift/templates/kofax-error-cronjobs.yaml
Just pulling in templates for dps/spd/vips error polling cronjobs, as well as standard jenkinsfile to clean up all pipelines/reference for infrastructure as code.
> Cronjobs and repo Jenkins file

- src/dps-email-poller/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailpoller/email/services/EmailService.java
- src/dps-email-poller/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailpoller/email/services/EmailServiceImpl.java
- src/dps-email-poller/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailpoller/scheduler/EmailPoller.java
- src/dps-email-poller/src/test/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailpoller/email/services/EmailServiceImplTest.java
- src/dps-email-poller/src/test/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailpoller/scheduler/EmailPollerPollForEmailsTest.java
- fix issue with reading attachments
Run locally + unit tests
> Refactored get attachment

- src/dps-email-poller/openshift/templates/jenkinsfile
- src/dps-email-worker/openshift/templates/jenkinsfile
- src/dps-notification-service/openshift/templates/jenkinsfile
- src/dps-payment-service/openshift/templates/jenkinsfile
- src/dps-registration-api/openshift/templates/jenkinsfile
- src/dps-validation-service/openshift/templates/jenkinsfile
- src/figaro-validation-service/openshift/templates/jenkinsfile
- src/spd-notification-worker/openshift/templates/jenkinsfile
- src/vips-notification-worker/openshift/templates/jenkinsfile
Had to add a context directory specific path to jenkins files for each
> Jenkins Files for days

- src/dps-notification-service/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsnotificationservice/WebServiceConfig.java
- src/dps-notification-service/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsnotificationservice/WebServiceProperties.java
- src/dps-notification-service/src/main/resources/application.properties
- Possibility to change the xml namespace on incoming messages
Locally
> Added possibility to change namespace

- src/vips-notification-worker/src/main/resources/application.properties
- Fix environment variable name
N/A
> fix username env variable

- src/vips-notification-worker/src/main/java/ca/bc/gov/open/pssg/rsbc/vips/notification/worker/Keys.java
- Removing an unused key
No test
> Removed unused key

- src/libs/figaro-ords-client/src/main/java/ca/bc/gov/open/pssg/rsbc/figaro/ords/client/document/DpsDocumentRequestBody.java
- src/spd-notification-worker/src/main/java/ca/bc/gov/open/pssg/rsbc/spd/notification/worker/OutputNotificationConsumer.java
- Adding more logs
Running Unit Tests
> refactored logging

- src/libs/dps-files/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/files/FileInfo.java
- src/spd-notification-worker/src/main/java/ca/bc/gov/open/pssg/rsbc/spd/notification/worker/OutputNotificationConsumer.java
- src/spd-notification-worker/src/test/java/ca/bc/gov/open/pssg/rsbc/spd/notification/worker/OutputNotificationConsumerTest.java
- fix payload to move files
Locally running unit tests
> updated call to accept filename

- src/vips-notification-worker/src/main/java/ca/bc/gov/open/pssg/rsbc/vips/notification/worker/OutputNotificationConsumer.java
> vips: spelling error

- src/libs/dps-files/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/files/FileInfo.java
- src/libs/dps-files/src/test/java/ca/bc/gov/open/pssg/rsbc/dps/files/FileInfoTest.java
- src/libs/dps-files/src/test/java/ca/bc/gov/open/pssg/rsbc/dps/files/FileServiceImplTest.java
- src/spd-notification-worker/src/main/java/ca/bc/gov/open/pssg/rsbc/spd/notification/worker/OutputNotificationConsumer.java
- src/spd-notification-worker/src/test/java/ca/bc/gov/open/pssg/rsbc/spd/notification/worker/OutputNotificationConsumerTest.java
- src/vips-notification-worker/src/main/java/ca/bc/gov/open/pssg/rsbc/vips/notification/worker/OutputNotificationConsumer.java
- fix issue with different folder names
> fix issue with folder name

- src/libs/figaro-ords-client/src/main/java/ca/bc/gov/open/pssg/rsbc/figaro/ords/client/document/DocumentServiceImpl.java
- Adding more debug statements to help understanding issue with figaro
N/A
> api: printing request in debug mode

- src/spd-notification-worker/src/main/java/ca/bc/gov/open/pssg/rsbc/spd/notification/worker/OutputNotificationConsumer.java
- Setting up some default values for the different party ids.
Local test only
> Set some default values for ids

- src/vips-notification-worker/pom.xml
- src/vips-notification-worker/src/main/java/ca/bc/gov/open/pssg/rsbc/vips/notification/worker/OutputNotificationConsumer.java
- src/vips-notification-worker/src/main/java/ca/bc/gov/open/pssg/rsbc/vips/notification/worker/health/HealthCheck.java
- src/vips-notification-worker/src/test/java/ca/bc/gov/open/pssg/rsbc/vips/notification/worker/OutputNotificationConsumerTest.java
- src/vips-notification-worker/src/test/java/ca/bc/gov/open/pssg/rsbc/vips/notification/worker/health/HealthCheckTest.java
> fixing vips worker deps

- src/dps-email-poller/pom.xml
- src/dps-email-worker/pom.xml
- src/dps-notification-service/pom.xml
- src/dps-payment-service/pom.xml
- src/dps-registration-api/pom.xml
- src/dps-validation-service/pom.xml
- src/figaro-validation-service/pom.xml
- src/libs/dfcms-ords-client/pom.xml
- src/libs/dps-bom/pom.xml
- src/libs/dps-cache-starter/pom.xml
- src/libs/dps-commons/pom.xml
- src/libs/dps-email-client/pom.xml
- src/libs/dps-files/pom.xml
- src/libs/dps-messaging-starter/pom.xml
- src/libs/dps-monitoring/pom.xml
- src/libs/dps-notification/pom.xml
- src/libs/dps-sftp-starter/pom.xml
- src/libs/figaro-ords-client/pom.xml
- src/libs/otssoa-ords-client/pom.xml
- src/pom.xml
- src/spd-notification-worker/pom.xml
- src/vips-notification-worker/pom.xml
> Log4j Fix to v2.17.0

- src/dps-email-poller/pom.xml
- src/dps-email-worker/pom.xml
- src/dps-notification-service/pom.xml
- src/dps-payment-service/pom.xml
- src/dps-registration-api/pom.xml
- src/dps-validation-service/pom.xml
- src/figaro-validation-service/pom.xml
- src/libs/dfcms-ords-client/pom.xml
- src/libs/dps-bom/pom.xml
- src/libs/dps-cache-starter/pom.xml
- src/libs/dps-commons/pom.xml
- src/libs/dps-email-client/pom.xml
- src/libs/dps-files/pom.xml
- src/libs/dps-messaging-starter/pom.xml
- src/libs/dps-monitoring/pom.xml
- src/libs/dps-notification/pom.xml
- src/libs/dps-sftp-starter/pom.xml
- src/libs/figaro-ords-client/pom.xml
- src/libs/otssoa-ords-client/pom.xml
- src/pom.xml
- src/spd-notification-worker/pom.xml
- src/vips-notification-worker/pom.xml
> log4j update

- src/dps-validation-service/pom.xml
- src/libs/dps-bom/pom.xml
> Jackson Databind fix

- src/dps-email-poller/pom.xml
- {List all the changes, if possible add the jira ticket #}
> Heap Space Increase

- .github/workflows/deploy.yml
- .github/workflows/dev-dps-email-poller.yml
- .github/workflows/dev-dps-notification-service.yml
- .github/workflows/dev-dps-payment-service.yml
- .github/workflows/dev-dps-registration-api.yml
- .github/workflows/dev-dps-validation-service.yml
- .github/workflows/dev-email-worker.yml
- .github/workflows/dev-figaro-validation-service.yml
- .github/workflows/dev-spd-notification-worker.yml
- .github/workflows/dev-vips-notification-worker.yml
deploy - used for deployment - build and push image to OC other modules workflow - build docker image -triggered by merge/commit to main branch
> workflow fixes

- src/dps-email-worker/pom.xml
https://stackoverflow.com/questions/60694091/error-creating-bean-when-i-run-spring-boot-application
> Resolve Jackson Conflict

- src/dps-email-poller/src/main/java/ca/bc/gov/open/pssg/rsbc/dps/dpsemailpoller/scheduler/EmailPoller.java
> add test data

- Dockerfile
> missing quote

- src/dps-email-poller/pom.xml
- src/dps-email-worker/pom.xml
- src/dps-notification-service/pom.xml
- src/dps-payment-service/pom.xml
- src/dps-validation-service/pom.xml
- src/figaro-validation-service/pom.xml
- src/libs/dfcms-ords-client/pom.xml
- src/libs/dps-bom/pom.xml
- src/libs/dps-cache-starter/pom.xml
- src/libs/dps-commons/pom.xml
- src/libs/dps-email-client/pom.xml
- src/libs/dps-files/pom.xml
- src/libs/dps-messaging-starter/pom.xml
- src/libs/dps-monitoring/pom.xml
- src/libs/dps-notification/pom.xml
- src/libs/dps-sftp-starter/pom.xml
- src/libs/figaro-ords-client/pom.xml
- src/pom.xml
- src/report/pom.xml
- src/spd-notification-worker/pom.xml
- src/vips-notification-worker/pom.xml
> change version from 0.5.0 to 0.5.1
